### ISSUE TITLE
cannot open created .pkpass with valid certs when using PKFileBasedSigningUtil

### ISSUE THREAD

**Issue by jonniedarko** [drallgood/jpasskit#100]
I generate the pk pass as follows:
```java
PKSigningInformation pkSigningInformation = new  PKSigningInformationUtil()
				.loadSigningInformationFromPKCS12AndIntermediateCertificate(
				"/path/to/pass.p12",
				"password",
				"/path/to/pass/wwdr.pem"
		);

PKFileBasedSigningUtil pkSigningUtil = new PKFileBasedSigningUtil();
String tempPath = "/tmp/mypass.raw";
PKPassTemplateFolder   passTemplate        = new PKPassTemplateFolder(tempPath);
byte[] signedAndZippedPkPassArchive = pkSigningUtil.createSignedAndZippedPkPassArchive(pass, passTemplate, pkSigningInformation);
ByteArrayInputStream inputStream = new ByteArrayInputStream(signedAndZippedPkPassArchive);
String fileName = "/tmp/pass.pkpass";
File passZipFile = new File(fileName);
IOUtils.copy(inputStream, new FileOutputStream(passZipFile));
```

but I can't open the resulting .pkpass. It is not a certificate issue because I can use the same pass.p12, password, and wwdr.pem to create a .pkpass in PHP using this [library]( https://github.com/tschoffelen/PHP-PKPass) and I can unzip and everything is generated fine. I can only guess it is a signature issue but I cannot understand why

**Comment by jonniedarko** [comment]
It does work when using `PKInMemorySigningUtil`

**Comment by drallgood** [comment]
Hi @jonniedarko 
Not sure exactly what's going on.
Did you try to check the created pass with the `signpass` util? https://developer.apple.com/services-account/download?path=/iOS/Wallet_Support_Materials/WalletCompanionFiles.zip

If you like, I can also have a look. All I need is the generated pass.

**Comment by jonniedarko** [comment]
So I was able to verify the pass created with PKInMemorySigningUtil using the preview on mac but not with the PKFileBasedSigningUtil. Its not a blocker for me as I can just use the PKInMemorySigningUtil, Just thought I should raise the issue for clarity.

**Comment by drallgood** [comment]
Yeah. This sounds like a bug I would like to squash (if it is one)
The  tests I have so far didn't uncover any issues, so I'd really appreciate your help with figuring out what's going on

**Comment by jonniedarko** [comment]
​Let me know what I can do to help​

**Comment by onlyamir007** [comment]
hi guys,

im having same issue im able to create .pkpass im able unzip also but iphone don't understand not able to open

**Comment by drallgood** [comment]
@DerekFangming 
In your case the answer is pretty simple:

**Comment by drallgood** [comment]
@DerekFangming The answer is pretty simple in your case: 
Working:
```
$ ./signpass  -v working.pkpass 
Signature valid.
Certificates: (
	0: Apple Worldwide Developer Relations Certification Authority
	1: Pass Type ID: pass.com.fmning.WPI-CSA
)
Trust chain is valid.

*** SUCCEEDED ***
```
Not working:
```
$ ./signpass  -v notWorking.pkpass 
Pass is missing files listed in the manifest, {
    "._.DS_Store" = 5ab2bf7809050d011ea3edf4466af77fedb26112;
    "._en.lproj" = e7544378ba46326fdd35efaa875e443bdd4e5ae2;
    "._icon.png" = 70a792abf8ea933fd94d7228307a28d2ffc99731;
    "._icon@2x.png" = c28e0c0f334bd48534e26c615dfd1508d532acee;
    "._logo.png" = c28e0c0f334bd48534e26c615dfd1508d532acee;
    "._logo@2x.png" = c28e0c0f334bd48534e26c615dfd1508d532acee;
    "en.lproj/._.DS_Store" = 5ab2bf7809050d011ea3edf4466af77fedb26112;
}

*** FAILED ***
```

**Comment by drallgood** [comment]
Looks like it's including a bunch of dot files

**Comment by DerekFangming** [comment]
@drallgood Bluhhh realllllly????? Let me double check that but im banging my head on my desk right now lol

Thanks for the info!

**Comment by drallgood** [comment]
@DerekFangming Question is why those files would be in the manifest but not the zip file.
I looked at the code, but can't explain it yet.

**Comment by DerekFangming** [comment]
@drallgood [I did not change my code](https://github.com/DerekFangming/WPI_CSA_Service/blob/6c4070c5be97deef6b6ab2a8e7d8f19b63ba2f04/src/main/java/com/fmning/wcservice/controller/rest/TestController.java#L78) and it just failed. I'll have a look at your end to see what I can do. I'll make a PR if I find out why & fix it.
