### ISSUE TITLE
cannot Set stripColor

### ISSUE THREAD

**Issue by jonniedarko** [drallgood/jpasskit#102]
In Libraries on other platforms, I am able to set the `stripColor` the same way I can set `backgroundColor` but you do not seem to have this exposed in your library

**Comment by drallgood** [comment]
Hi @jonniedarko 
`stripColor` doesn't seem to be a valid key according to Apple's documentation, which is also why we don't support it.

See also: https://developer.apple.com/library/content/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/TopLevel.html#//apple_ref/doc/uid/TP40012026-CH2-SW6
