### ISSUE TITLE
Can not create the .pkPass getting error

### ISSUE THREAD

**Issue by BaluBabu** [drallgood/jpasskit#104]
During run time im getting this error, Can you please help me out to resolve this issue.
java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.ser.impl.SimpleFilterProvider.addFilter(Ljava/lang/String;Lcom/fasterxml/jackson/databind/ser/impl/SimpleBeanPropertyFilter;)Lcom/fasterxml/jackson/databind/ser/impl/SimpleFilterProvider;

**Comment by drallgood** [comment]
@BaluBabu 
Sounds like you're missing a dependency. Please make sure you have all necessary dependencies in your classpath.

**Comment by drallgood** [comment]
Closing because there was no further feedback
