### ISSUE TITLE
MacOs shows black QR-Code

### ISSUE THREAD

**Issue by datenmuehle** [drallgood/jpasskit#105]
If i generate a wallet and open the pkpass file on MacOS the QR-Code is completely black. As i find out the pass.json file inside the pkpass file contains a "barcode" and a "barcode**s**" element. So, as I understand the "barcode" element is outdated and schouldn't be used anymore. And if i remove this element from the pass.json file and put it into the pkpass file, MacOS is able to show the QR-Code in the right way!

**Comment by drallgood** [comment]
That is unfortunately a bug in MacOS then.
Apple clearly states that you should use both for backwards compatibility:
https://developer.apple.com/library/content/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/TopLevel.html#//apple_ref/doc/uid/TP40012026-CH2-SW5
