### ISSUE TITLE
java.lang.SecurityException: class "org.bouncycastle.cms.CMSProcessable"'s signer information does not match signer information of other classes in the same package

### ISSUE THREAD

**Issue by mayankaSethitekmindz** [drallgood/jpasskit#110]
Hello @uebi-belli , @drallgood

I am also facing similar kind of issue ,using jpasskit
java.lang.SecurityException: class "org.bouncycastle.cms.CMSProcessable"'s signer information does not match signer information of other classes in the same package
at java.lang.ClassLoader.checkCerts(ClassLoader.java:898)
at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668).
![capture](https://user-images.githubusercontent.com/38096129/42159775-92d7a0c0-7e12-11e8-88d3-6751bfc88705.PNG)

**Comment by mayankaSethitekmindz** [comment]
Hi

I am able to solve above issue.But Still my pass generated is not getting opened.Please suggest.

**Comment by drallgood** [comment]
@mayankaSethitekmindz 
Glad you were able to resolve this.

Please use the methods provided by Apple to debug issues related to passes not showing up correctly on device

Thanks
