### ISSUE TITLE
com.google.common.io.Files

### ISSUE THREAD

**Issue by jbagley94** [drallgood/jpasskit#112]
Currently got the code deploy and include guava-19.0-rc1.jar file in my deployment.  But the transaction is failing with 

java.lang.NoSuchMethodError: com.google.common.io.Files.hash(Ljava/io/File;Lcom/google/common/hash/HashFunction;)Lcom/google/common/hash/HashCode;

**Comment by drallgood** [comment]
well, that may be because we're actually on Guava version 24
See https://github.com/drallgood/jpasskit/blob/72e5d76a3a90b24e381b1eb38d52964f7efa4e84/jpasskit/pom.xml#L89
