### ISSUE TITLE
Vulnerability for commons-httpclient dependency in 0.0.9 version

### ISSUE THREAD

**Issue by manishaskani** [drallgood/jpasskit#113]
Vulnerability for commons-httpclient dependency in 0.0.9 version. Can you fix the milestone version with updated commons-httpclient pom or when can we expect the milestone version for 0.1.0 which is now a snapshot?

**Comment by drallgood** [comment]
@manishaskani I don't see an updated version, that we could upgrade to.
We're already on 3.1

**Comment by manishaskani** [comment]
@drallgood Our enterprise scans figured out that 3.1 version is vulnerable, so I wanted to ask you if you can update with the one you are using in 0.1.0-SNAPSHOT which is the below pasted pom, instead of the existing deprecated commons-httpclient-3.1.

<dependency>
	<groupId>org.apache.commons</groupId>
	<artifactId>commons-collections4</artifactId>
	<version>4.1</version>
</dependency>

**Comment by drallgood** [comment]
@manishaskani Ah. Not sure I can do anything about that. It's a dependency from a third-party.
Let me look into it

**Comment by drallgood** [comment]
I've removed the third-party dependency since it isn't really developed anymore. 
Now using pushy

see https://github.com/drallgood/jpasskit/commit/603a61778e23ab81b6ed7c53f66e8035767668a8

**Comment by manishaskani** [comment]
@drallgood  Is it available now in 0.0.9 version or in the Snapshot version 0.1.0 ? Because we are using it in our enterprise code so would be needing in milestone version i.e. 0.0.9 version.

**Comment by drallgood** [comment]
Only in the snapshot version.
I can release it within the next few days...

**Comment by manishaskani** [comment]
Hi @drallgood Is there any timeline for the release of milestone version of 0.1.0 ? We would be going live in 2 weeks. It would be great if you can release it soon. Kindly let me know if there is any timeline for the release. :)

**Comment by drallgood** [comment]
@manishaskani 
I had no immediate plans when to release it... so... I just did ;)
Should be available shortly

**Comment by manishaskani** [comment]
@drallgood  Thanks a lot! 👍 
I would need your suggestion in one of the scenarios I am using in my code. My basic necessity is to build & design apple passes & send it through email, so that users can add into their own apple wallet. Subsequently whenever the pass details get updated I want to notify the device using the device token with an empty push notification so that the wallet calls my application back for the latest version of the pass. Using the new approach in your jpasskit, which uses pushy internally, I am not able to figure out the "topic name" needed to be given to send this dummy notification to my users just to trigger a call back to my application for latest version. Any help here would be greatly appreciated ? :)

Thanks!

**Comment by drallgood** [comment]
Usually no topic name is required.
Everything else is easily doable. Just keep in mind that users can opt-out of such updates (or may not get it for some reason)
See: https://github.com/drallgood/jpasskit/blob/master/jpasskit/src/main/java/de/brendamour/jpasskit/apns/PKSendPushNotificationUtil.java
