### ISSUE TITLE
pknfc jpasskit,pass not getting opened

### ISSUE THREAD

**Issue by mayankaSethitekmindz** [drallgood/jpasskit#114]
Trying to generate a ios pass.Once i add code of nfc

PKStoreCard storeCard = new PKStoreCard();
storeCard.setPrimaryFields(primaryFields);
PKNFC nfc = new PKNFC();
nfc.setMessage("DUMMY_14589"); // account RFID -- DUMMY_XXXXXX
nfc.setEncryptionPublicKey("properkey="); 
I am unable to open the pass.once i remove this i am able to access my pkpass file. Can you Please suggest ,If i am missing out on something .

Although I am able to open same pass in android with Passwallet App +NFC Enabled
Regards Mayanka

**Comment by drallgood** [comment]
Hi @mayankaSethitekmindz 
Thank you for reaching out. 
Unfortunately, I really can't help you with that. As I don't have a valid NFC cert (or hardware) I haven't been able to properly test this functionality.

Please use the means mentioned in Apple's Wallet Guides to debug this issue

I'm going to close this issue until there's something we can do.
