### ISSUE TITLE
Failed to add pass 

### ISSUE THREAD

**Issue by priyanshiTiwari** [drallgood/jpasskit#116]
Error Domain=PKPassKitErrorDomain Code=1 "Failed to read data" UserInfo={NSLocalizedDescription=Failed to read data, NSUnderlyingError=0x6000039b5110 {Error Domain=NSCocoaErrorDomain Code=260 "The file “pass.json” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/Faisal.Dilawar/Library/Developer/CoreSimulator/Devices/1837CC0E-FB3D-4D8F-91BC-3898BF39F029/data/Containers/Data/Application/614DC1F4-86BE-4598-A47F-A6463B8979B8/Library/Caches/com.apple.Passbook/com.apple.Passbook/1282B9B6-2EFD-41DD-BC6A-7BC3FD724402.pkpass/pass.json, NSUnderlyingError=0x6000039b51d0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}}}

This issue is coming on dropping the .pkpass file on simulator. can you please tell what can be the reason for this?

**Comment by drallgood** [comment]
Hi @priyanshiTiwari 
Thanks for reaching out and sorry for not responding earlier.

Have you tried unzipping the pass to see whether the pass.json is even there?
You can also use Apple's signposts tool to check the validity of your pass.

**Comment by drallgood** [comment]
No response. closing
