### ISSUE TITLE
Externalize app identifier in PKSendPushNotificationUtil

### ISSUE THREAD

**Issue by drallgood** [drallgood/jpasskit#150]
See https://github.com/drallgood/jpasskit/blob/139ff8da55b4f92599d464e7206731fb611e49aa/jpasskit/src/main/java/de/brendamour/jpasskit/apns/PKSendPushNotificationUtil.java#L118

**Comment by stepio** [comment]
Good catch. As per Apple's documentation parameter `topic` (the one which you set as "com.example.myApp") should not be mandatory:

> The topic of the notification. When using token-based authentication, specify the bundle ID of the app. When using certificate-based authentication, the topic is usually your app's bundle ID. However, the topic may also correspond to the bundle ID of an Apple Watch complication or a background VoIP service. Look in the (1.2.840.113635.100.6.3.6) extension of your certificate to identify the possible topics for your push notifications. **If you omit the header and your certificate does not contain multiple topics, APNs uses your certificate’s Subject as the default topic.**

https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns

But `pushy` project decided to make them mandatory and won't change this as per https://github.com/relayrides/pushy/issues/348 and https://github.com/relayrides/pushy/issues/607:
> APNs protocol will be moving away from certificates and toward bare private keys in the near future, and we don't want to build dependence on a feature that we know is going away.
> I would describe the current behavior as a design decision more than an error.

In previous versions of pushy there was an utility to extract valid topic from certificate:
https://github.com/relayrides/pushy/blob/v0.7.3/pushy/src/test/java/com/relayrides/pushy/apns/TopicUtil.java#L17
Although now it's removed from the project, we can add tis utility to jpasskit and use it to extract the valid topic name from the provided certificate.

What do you think?

**Comment by drallgood** [comment]
Sounds like a plan

**Comment by stepio** [comment]
So... @drallgood , closing this one?

**Comment by drallgood** [comment]
yep
closed with #157
