### ISSUE TITLE
relevantDate is incorrectly formatted

### ISSUE THREAD

**Issue by anonymoustravis** [drallgood/jpasskit#181]
When I specify a relevantDate property, the value appears to be improperly formatted.  It looks like this was previously fixed in https://github.com/drallgood/jpasskit/commit/79c6e7bca2c14cd2e7e70654c7d9c645607f6297, but the objectMapper format has since been moved to a different class and changed to StdDateFormat.  Apple does not allow milliseconds in their date format and as a result the pass wont open.

Steps:

Create pass
Set date: pass.setRelevantDate(new Date())
View "relevantDate" in pass.json file
Expected:
"relevantDate": "2019-04-30T22:00:00+0000"

Actual:
"relevantDate": "2019-04-30T22:00:00.000+0000"

Thank you so much!

**Comment by igostavro** [comment]
having same issue. anyone have a fix or workaround? @anonymoustravis

**Comment by stepio** [comment]
Hello, sorry for missing this, my bad.

Yes, Apple clearly states that you're right, for example here:
https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html
> To provide a relevant date, add the relevantDate key at the top level of the pass. A pass can have up to one relevant date. Its value is a W3C timestamp, either a complete date plus hours and minutes or a complete date plus hours, minutes, and seconds.

It's a compatibility issue, which came from migration to the newer Jackson, other Jackson users had similar problems:
https://github.com/FasterXML/jackson-databind/issues/1786

As a workaround you may add next option to the ObjectMapper's configuration:
```java
        jsonObjectMapper.configOverride(Date.class).setFormat(JsonFormat.Value.forPattern("yyyy-MM-dd'T'HH:mm:ssZ"));
```

At least this helped me with such a trivial test:
```java
    @Test
    public void testDatesSerialization() throws Exception {
        String originalDate = "2019-04-30T22:00:00+0000";
        SimpleDateFormat parser = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ");
        Date date = parser.parse(originalDate);
        String formatted = this.pkInMemorySigningUtil.objectWriter.writeValueAsString(date);
        formatted = formatted.substring(1, formatted.length() - 1);
        Assertions.assertThat(formatted).isEqualTo(originalDate);
    }
```

Complete method `configureObjectMapper` in `PKAbstractSigningUtil` looks as follows after the fix:
```java
    protected ObjectWriter configureObjectMapper(final ObjectMapper jsonObjectMapper) {
        jsonObjectMapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
        jsonObjectMapper.setDateFormat(new StdDateFormat());
        jsonObjectMapper.configOverride(Date.class).setFormat(JsonFormat.Value.forPattern("yyyy-MM-dd'T'HH:mm:ssZ")); // <--- FIX HERE !
        SimpleFilterProvider filters = new SimpleFilterProvider();

        // haven't found out, how to stack filters. Copying the validation one for now.
        filters.addFilter("validateFilter", SimpleBeanPropertyFilter.serializeAllExcept("valid", "validationErrors"));
        filters.addFilter("pkPassFilter", SimpleBeanPropertyFilter.serializeAllExcept("valid", "validationErrors", "foregroundColorAsObject",
                "backgroundColorAsObject", "labelColorAsObject", "passThatWasSet"));
        filters.addFilter("barcodeFilter",
                SimpleBeanPropertyFilter.serializeAllExcept("valid", "validationErrors", "messageEncodingAsString", "validInIosVersionsBefore9"));
        filters.addFilter("charsetFilter", SimpleBeanPropertyFilter.filterOutAllExcept("name"));
        jsonObjectMapper.setSerializationInclusion(Include.NON_NULL);
        jsonObjectMapper.addMixIn(Object.class, ValidateFilterMixIn.class);
        jsonObjectMapper.addMixIn(PKPass.class, PkPassFilterMixIn.class);
        jsonObjectMapper.addMixIn(PKBarcode.class, BarcodeFilterMixIn.class);
        jsonObjectMapper.addMixIn(Charset.class, CharsetFilterMixIn.class);
        return jsonObjectMapper.writer(filters);
    }
```

Hope this helps for now, I'll submit the PR later.

**Comment by drallgood** [comment]
@stepio is this fixed? Not sure what the status of this is

**Comment by stepio** [comment]
@drallgood, thanks for adding this fix! I was a little bit busy, so was not able to complete this myself.

**Comment by drallgood** [comment]
No worries @stepio I've been pretty busy myself!
