### ISSUE TITLE
Upgrade Passkit to version 0.1.1

### ISSUE THREAD

**Issue by BESAFX** [drallgood/jpasskit#192]
I need to upgrade current Passkit library used on my server from version 0.0.9 to version 0.1.1, what is changlogs in details that i will required to change like APNs.
I tried upgrading, but it gives me many errors.

**Comment by drallgood** [comment]
Hey @BESAFX 
Can you give us a couple of examples for errors you're seeing?
We mostly removed deprecated methods and switched the APNS implementation to pushy. 
So there should only be minimal changes necessary for you.

**Comment by BESAFX** [comment]
Hey @drallgood 
Thanks for your quick replay, first issues happened when trying deserialize PKField object, i see that you change data type of field [value] in PKField class from [Object] into [Serializable] and [attributedValue] field too, and these changes i think the main reason for this issues : 
`java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of java.io.Serializable: abstract type
s either need to be mapped to concrete types, have custom deserializer, or contain additional type information
!  at [Source: [{"dataDetectorTypes":[],"key":"","label":"NAME","value":"UPLAND"}]; line: 1, column: 58] (through reference chain: java.util.ArrayList
[0]->de.brendamour.jpasskit.PKField["value"])`

**Comment by drallgood** [comment]
@BESAFX Thanks.

There was indeed a bug when reading a pass.json
Should be fixed on master with ee7c6a5

**Comment by BESAFX** [comment]
@drallgood  Thank You

But is this commit on latest release now, or how can get this changes to my local code :)

**Comment by drallgood** [comment]
@BESAFX You can use the snapshot version to test this: `0.2.0-SNAPSHOT`
