### ISSUE TITLE
Can't update my pkpass file

### ISSUE THREAD

**Issue by monkeyooo** [drallgood/jpasskit#237]
Sorry for bothering you.
I had used the sample code from this link.
However, I can't update the object successfully.
It gave me these info, but didn't change the amount on my simulator.
The log on my server's console:
`org.restlet.engine.security.AuthenticatorUtils parseResponse`
`Couldn't find any helper support the HTTP_ApplePass challenge scheme.`
`org.restlet.engine.log.LogFilter afterHandle`
`192.1.1.1	-	::	8083	GET	/ApplePay/ServerStart/v1/passes/pass.com.de/123456781200	-	404	439	0	18	http://192.1.1.1:8083	passd/1.0 CFNetwork/974.2.1 Darwin/17.7.0	-`
I just change the port key and doesn't use the SSL protocol.
How could I update my balance?
It seems the simulator connect my server successfully but can't find the default scheme.

Thank you!

**Comment by drallgood** [comment]
You sure the URL you're using is correct?
`GET /ApplePay/ServerStart/v1/passes/pass.com.de/123456781200` returns a 404

**Comment by monkeyooo** [comment]
Yes, I think it is correct.
Is there any way to check the URL is working or correct for the pass?
I get 404 return code on my server's console when I update the pass on my simulator.

Thank you

**Comment by drallgood** [comment]
Just use your browser or a tool like Postman. It's a standard REST api, so you can just debug it like any other API.
When you call above endpoint you should get a pass back.

**Comment by monkeyooo** [comment]
Yes, I had used it.
The server is working.
I want to know could pkpass pass using a server URL which is not verify in simulator.
The simulator seems didn't check the URL and can add into the wallet.
Thanks!

**Comment by drallgood** [comment]
Yeah. Don't use the simulator. It's not really reliable/working. We've had multiple reports like this.
Please test it with a real device

**Comment by drallgood** [comment]
Closing this issue because it's not really anything we can control
