### ISSUE TITLE
JPasskit server update pass failed

### ISSUE THREAD

**Issue by monkeyooo** [drallgood/jpasskit#242]
Sorry for bothering again.
I'm trying to update my pkpass on my server and using the sample which provided on this project.
However, when I refresh my pass on my phone/simulator, the server gives me this response:
`10:26:32.386 [Restlet-773989906] ERROR ApplePay.Server.PKPassResource - Error when parsing response to JSON:
java.lang.IllegalStateException: Failed to read pass from JSON file
	at ApplePay.Server.PKRestletServerResourceFactory$2.handleGetLatestVersionOfPass(PKRestletServerResourceFactory.java:118)
	at ApplePay.Server.PKPassResource.getLatestVersionOfPass(PKPassResource.java:75)
`

`Caused by: java.io.FileNotFoundException: passes\coupons.raw\pass.json `

Probably because these code:
`public PKPassResource getPKPassResource() {
		return new PKPassResource("passes/coupons.raw") `
It breaks when go this line
`PKPass pass = jsonObjectMapper.readValue(new File("passes/coupons.raw/pass.json"), PKPass.class);`
Could you please tell me where the files come from?
`passes/coupons.raw/pass.json`
`passes/coupons.raw`

**Comment by monkeyooo** [comment]
After testing, I know `return new PKPassResource("passes/coupons.raw")` is the icons directory path.
And `PKPass pass = jsonObjectMapper.readValue(new File("passes/coupons.raw/pass.json"), PKPass.class);` seems like the json which had been create from jpasskit.
I using the json from the pkpass file, however, it always gives me the error message:
` Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: 
 Cannot construct instance of `java.io.Serializable` 
 (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, 
 have custom deserializer, or contain additional type information
 at [Source: (File); line: 1, column: 466] 
 (through reference chain: ApplePay.Pass.PKPass["coupon"]
 ->ApplePay.Pass.passes.PKCoupon["headerFields"]
 ->java.util.ArrayList[0]
 ->ApplePay.Pass.PKFieldBuilder["value"])`
So I create a new a pass and set all the value from the database.
I still don't know `new File("passes/coupons.raw/pass.json")` this file comes from.

**Comment by drallgood** [comment]
Clearly `PKPassResource` is an abstract class. 
See also https://github.com/drallgood/jpasskit/blob/master/jpasskit.server/src/main/java/de/brendamour/jpasskit/server/PKPassResource.java

You have to use one of the provided subclasses, or provide your own implementation (depending on your needs).

Also: usually you won't read the pass from a JSON file but rather generate it using the provided classes.
