### ISSUE TITLE
Apns push notification

### ISSUE THREAD

**Issue by drenda** [drallgood/jpasskit#249]
Hi, I'd like to know if the PKSendPushNotificationUtil.java is intended to send push notification to used that installed a Pass as described here: https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns or it's just a notification for update the pass in the user's device.

Thanks

**Comment by drallgood** [comment]
@drenda It's only intended to be used to trigger updates of passes.
