### ISSUE TITLE
When register device, request can't get json token

### ISSUE THREAD

**Issue by monkeyooo** [drallgood/jpasskit#251]
I built a pkpass and added it to my Device.
However, when I clicked "add" button, there was a NPE occur.
It seems happen in these two line:
`String jsonPushToken = entity.getText();`
`PKPushToken pkPushToken = jsonObjectMapper.readValue(jsonPushToken, PKPushToken.class)`
`entity.getText()` This function will get null value.
However, I used PostMan to send a register message, this method could get the request body value.

Because I'm going to send APNs notification, I need this variable to push notification.
Is there anyone encounter the same issue?

**Comment by drallgood** [comment]
Can you see what the iPhone is sending?
Sounds like the payload is missing

**Comment by monkeyooo** [comment]
Yes, I think payload is missing.
So, is there anyway to see the message sending from iPhone?
I printed all the received variables but I still can't get the payload reference.

**Comment by drallgood** [comment]
Depends. There are many options. You can run the server in debug mode in your IDE. Or use a tool like tcpdump. 
Standard stuff to debug communication and java servers

**Comment by monkeyooo** [comment]
However, Is there any way that I could connect iPhone to Mac and see the logs?
Or I only could write a method to see the message in my servers?

**Comment by drallgood** [comment]
you mean the iPhone’s logs? yeah. you can do that in XCode. 
But if you want to debug the request that has to happen server side obviously. 
If you run the server on your mac (e.g in your IDE), it’s relatively easy to do

**Comment by monkeyooo** [comment]
However, I tried many ways to see the request, it seems the device didn't send the token.
Because I use the POSTMAN to send message, the method `entity.getText()` could get the json body/payload.
Here is the request that I receive from iPhone:
`entity.getText() : null`

`entity.toString() : [application/json]`

`request.getEntityAsText() : null`
`request.getAttributes().toString() : {org.restlet.startTime=1583389416595, deviceLibraryIdentifier=xxxxxxxx, serialNumber=12345, passTypeIdentifier=pass.com.xxx.demo, org.restlet.http.headers=[[Accept-encoding: gzip, deflate, br], [Accept: */*], [Connection: close], [Host: demo.xxxx.com], [User-agent: passd/1.0 CFNetwork/1121.2.2 Darwin/19.3.0], [Authorization: ApplePass AUTHTOKEN], [Content-type: application/json], [Accept-language: en-us], [X-forwarded-for: 111.10.8.250], [Content-length: 80]]} `

`request.getChallengeResponse().getClientNonce() : null`

`request.getEntity().getText() : null`

`request.getCurrent().getEntityAsText() : null`

`request.getCurrent().getEntity().getText() : null`

`Representation test = getRequestEntity();`

`test.getText() : null`

`test.getStream().toString() : null`

And I found a similar problem on [stackoverflow](https://stackoverflow.com/questions/16722210/restlet-post-request-does-not-provide-json-data-passed).
But it seems didn't solve it.

**Comment by drallgood** [comment]
Have a look at the raw request, so before Restlet gets it. You can get it using one of the ways I mentioned above

**Comment by monkeyooo** [comment]
I used tcpdump to catch the request and I can see the `pushToken ` in the request.
Therefore, It seems like the framework can't get the payload field.

**Comment by drallgood** [comment]
Alright. Thanks.
Do you think you could figure out why that is happening?
I don’t know when I will have time to look into this...

**Comment by monkeyooo** [comment]
I'm trying to figure out this problem.
I think it's cause by restlet can't receive the json payload. 
Like the problem from stackoverflow that I provided before.

**Comment by drallgood** [comment]
What version of jPasskit are you using? @monkeyooo 
Have you tried it with the 0.2.0-SNAPSHOT?

**Comment by monkeyooo** [comment]
Actually, I didn't use the jPasskit jar.
I copied all the files and overwrite it three months ago.
But I didn't modify the jPasskit part.
And all the necessary jar is using the latest version.
My restlet version is 2.4.0

**Comment by monkeyooo** [comment]
I think it's cause by restlet version.
After updating, it works.

**Comment by drallgood** [comment]
Awesome. Guess we hit a bug
