### ISSUE TITLE
PKSigningInformationUtil loading resources from fat .jar

### ISSUE THREAD

**Issue by drenda** [drallgood/jpasskit#254]
I'd like to know if this class is intended to be able to load resources from a a far jar.
I deploy my application with Spring Boot into a fat .jar and during the generation of the certificate, I load resourced from the .jar.

It doesn't work and I get a file not found exception. I want just know if it could work in that way or if I've to provide resources in a different way: while PKPassTemplateInMemory accept an inputStream, PKSigningInformationUtil accept just a path.

Thanks

**Comment by drallgood** [comment]
Have a look at https://github.com/drallgood/jpasskit/blob/master/jpasskit/src/main/java/de/brendamour/jpasskit/signing/PKSigningInformationUtil.java

It supports streams and also loading from the class path

**Comment by jnavarrodev** [comment]
Hi @drallgood, I have been able to fix the loading of resources using inputStream as you said. 

How could I load the folder for PKPassTemplateFolder? is there any way? It does not work when running de application as a jar.
