### ISSUE TITLE
Add documentation to add strings file with PKPassTemplateInMemory

### ISSUE THREAD

**Issue by drenda** [drallgood/jpasskit#255]
Hi, could you provide some documentation about how to add strings files to the bundle?

Is not clear to me if it's enough to do something like this:

`pkPassTemplateInMemory.addFile("strings", Locale.ITALY, inputStream);`

Is there any utility to create an in memory Strings file?

Thanks very much

**Comment by drallgood** [comment]
Should be fine.
No there's no utility because it's nothing jPasskit can do. Has to be your responsibility

PRs for documentation are always welcome ;)

**Comment by drenda** [comment]
Thanks for your reply. How can I tell jpasskit I want to use label picking them from string file? I see in the field I can just set label as a string.

I tried to set it as the key in the string file but it didn't work.

I created my language file as follow:

```
            private InputStream createLanguageFile(Locale locale) {
        if (locale.equals(Locale.ITALIAN)) {
            StringBuffer stringBuffer = new StringBuffer();
            stringBuffer.append("\"name\":\"Nome\";");
            stringBuffer.append("\"enrolledsince\":\"Iscritto dal\";");
            stringBuffer.append("\"web\":\"Sito web\";");
            stringBuffer.append("\"phone\":\"Telefono\";");
            stringBuffer.append("\"news\":\"Novità\";");
            return new ByteArrayInputStream(stringBuffer.toString().getBytes());
        } else if (locale.equals(Locale.ENGLISH)) {
            StringBuffer stringBuffer = new StringBuffer();
            stringBuffer.append("\"name\":\"Name\";");
            stringBuffer.append("\"enrolledsince\":\"Enrolled since\";");
            stringBuffer.append("\"web\":\"Web site\";");
            stringBuffer.append("\"phone\":\"Phone\";");
            stringBuffer.append("\"news\":\"News\";");
            return new ByteArrayInputStream(stringBuffer.toString().getBytes());
        }
        return null;
    }
```

and I added them in my pass in this way:

 ```
            pkPassTemplateInMemory.addFile("strings", Locale.ITALY, italianLanguage);
            pkPassTemplateInMemory.addFile("strings", Locale.ENGLISH, englishLanguage);
```

Thanks

**Comment by drallgood** [comment]
I think your strings file is not valid:
https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/LoadingResources/Strings/Strings.html

Other than that it should work like that. The devices will read the appropriate strings based on locale and the provided label.

**Comment by drallgood** [comment]
Also. The file should be named `pass.strings` according to:
https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html

**Comment by drallgood** [comment]
Hope that fixed it. Closing issue for now.
Please feel free to contribute documentation for how to add strings files
