### ISSUE TITLE
What is the best usage for createSignedAndZippedPkPassArchive

### ISSUE THREAD

**Issue by dnldmp** [drallgood/jpasskit#259]
Hi,

I cant't use createSignedAndZippedPkPassArchive becase always returns nullPointerException.

What is the best form to use or how should i use?

I've tried a lot of different forms.

Thank you!

**Comment by drallgood** [comment]
Umm. Not sure I can be of much help there.
You have to look at your `NullPointerException` and figure out what's missing. Something is null that shouldn't be. 

See also our sample code...
