### ISSUE TITLE
Support Auxiliary Fields Row Parameter

### ISSUE THREAD

**Issue by chris-maheu** [drallgood/jpasskit#269]
https://developer.apple.com/videos/play/wwdc2018/720/

See page 59 of the presentation slides: https://devstreaming-cdn.apple.com/videos/wwdc/2018/720gofzcqcp431kcasf/720/720_wallet_and_apple_pay_creating_great_customer_experiences.pdf?dl=1

```
"auxiliaryFields": [
 {
 "label": "Date",
 "key": "Date",
 "value": “June 9, 2018”,
 “row”: 0
 },
 {
 "label": "Section",
 "key": "Section",
 "value": “10”,
 "row": 1
 }
]
```

“Row” can only be used in auxiliary fields in an event ticket type pass
Only values of 0 and 1 supported
Coming in a future seed
On older versions, “row” is ignored
Auxiliary fields are then displayed on one row up to the limit of fourth fields per row
Consider this when designing your passes

**Comment by drallgood** [comment]
Took me a while to find the documentation for this.
Their "reference page" is woefully outdated.

Anyhow, it's here:
https://developer.apple.com/documentation/walletpasses/passfields/auxiliaryfields#properties
