### ISSUE TITLE
PKPass.setBarcode method

### ISSUE THREAD

**Issue by isc-yzheng** [drallgood/jpasskit#306]
Hi, I follow the instruction in mini-tutorial.txt,  and pasted the code to a java class. It says "The method setBarcode(PKBarcode) is undefined for the type PKPass"

Could you please help me out?

**Comment by drallgood** [comment]
That's correct. It should be setBarcodes(List<PKBarcode>)

See also https://github.com/drallgood/jpasskit/blob/master/jpasskit/src/main/java/de/brendamour/jpasskit/PKPass.java

I'll fix the tutorial when I find time. Thanks for reporting this

**Comment by isc-yzheng** [comment]
Yes, so what I did is I created a new list of PKBarcode and put the barcode in the list, then call setBarcodes(list)

**Comment by drallgood** [comment]
Adapted the tutorial. Thanks for the heads up @isc-yzheng
