### ISSUE TITLE
Cannot create valid passes with AppleWWDRCAG3.cer

### ISSUE THREAD

**Issue by rmunroe** [drallgood/jpasskit#312]
Apple has stated [here](https://developer.apple.com/support/expiration/) that the existing AppleWWDRCA.cer file should be replaced with the newer AppleWWDRCAG3.cer (linked on that page). However, when I replace the old WWDR cert with this newer one, the passes created by jpasskit fail [validation](https://pkpassvalidator.azurewebsites.net/) by reporting a failed "WWDR Certificate Subject." Additionally I cannot open the passes on an iOS device / simulator.

We still have 2 years before AppleWWDRCA.cer expires, however we would like to use AppleWWDRCAG3.cer sooner than later. Is this certificate type unsupported? And if so, will jpasskit be able to support it within the next 2 years?

**Comment by rmunroe** [comment]
To answer my own question, that Apple notification page does explicitly say, which I missed until 1 minute after submitting this issue:

Apple Push Notification service certificates **including the Pass Type ID certificate** will be updated in fall 2021 and will be associated to a new intermediate certificate focused on Push Notification services. At this time, we will be reducing the number of certificates required to interact with APNs. Until this update, **continue to use the existing intermediate certificate, which expires in February 2023**.

**Comment by drallgood** [comment]
Glad you caught it :)

But yes, we will still support it. Mostly you will just need to change the certificate you provide
