### ISSUE TITLE
PKField validation error.

### ISSUE THREAD

**Issue by paynes** [drallgood/jpasskit#318]
Hi,

I think that I find bug in validation of PKField. From [docs](https://developer.apple.com/library/archive/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/FieldDictionary.html#//apple_ref/doc/uid/TP40012026-CH4-SW5) _changeMessage_ can be _localizable format string_. That means two valid values: 

-  "_Change message with placeholder %@_" 
- "_changeMessage.localization.key_"

When I pass second value to changeMessage field, then validation fails because is missing placeholder. 

I suggest remove _checkChangeMessageContainsPlaceholder_ method from validation.

**Comment by drallgood** [comment]
Hey @paynes 
Thanks for reporting this. You're right. I think I misread the statement in the docs. The string has to contain it but obviosuly the localization key doesn't
