### ISSUE TITLE
Prepare 0.2.0 release

### ISSUE THREAD

**Issue by drallgood** [drallgood/jpasskit#320]
- [x] Merge remaining PRs
- [x] Check Docs
- [x] Check Release Notes
- [x] Migrate to GitHub Actions (TravisCI is broken)
- [x] Finish merging open MRs (library upgrades)
- [x] Stage Release

**Comment by sebphil** [comment]
Hello, can we have an ETA on this release please? I'm eagerly waiting for it to upgrade my dependency to bouncycastle, which is stuck at 1.68 until I can point to a jpasskit version that depends on bouncycastle 1.69. Thanks a lot for your work by the way!

**Comment by drallgood** [comment]
@sebphil Sorry. Not had too much time until now.
I still need to finish migrating to GitHub Actions so I can merge the last MRs.
After that it should be quick & easy :)

**Comment by drallgood** [comment]
And done :)

**Comment by sebphil** [comment]
thank you very much!
