### ISSUE TITLE
Link in the README doesn't work anymore

### ISSUE THREAD

**Issue by paraita** [drallgood/jpasskit#338]
I noticed the link pointing to the Apple Dev Documentation doesn't work:

> PKPersonalizePassResource is used to store the signup information for a rewards program (see https://developer.apple.com/library/prerelease/content/documentation/UserExperience/Conceptual/PassKit\_PG/PassPersonalization.html)

**Comment by drallgood** [comment]
Thanks for catching this!
I'll have a look around for a replacement

**Comment by diegotovaresp** [comment]
i have a problem when i add the webserviceURL and authenticationToken , the pass doesnt work ...

**Comment by drallgood** [comment]
fixed with #430
