### ISSUE TITLE
Not able to sign using verbose option

### ISSUE THREAD

**Issue by mgkansal** [drallgood/jpasskit#366]
Hello there,

I am working on a project which requires to sign a pkpass using verbose option, like this: signpass -p {cardName}.pass --verbose.  However, in the PKAbstractSigningUtil or PKFileBasedSigningUtil, I could not find a place where to provide that verbose option. Could you please let me know if there is such option available or how can I customize it?

Thank you!

**Comment by drallgood** [comment]
We don't wrap signpass but rather implement our own signing service (using the information provided by Apple in regards to how to create a valid pass)
So I can’t tell you what to do. 

Additionally, I don't think Apple's signpass util has a ‘--verbose’ flag?
At least it's not in the sources

**Comment by mgkansal** [comment]
Got it. Thanks for the quick response!
