### ISSUE TITLE
Not able to ignore certain fields that are not required

### ISSUE THREAD

**Issue by mgkansal** [drallgood/jpasskit#367]
I am trying to generate a PKPass, in which I don't need to generate certain fields, such as beacons and locations.  While populating the PKPass, I tried to specifically set those fields to null.  But in the generated pass, I still get these fields like this: 
"beacons": [],
"locations": [],

I even tried to extend PKPass object.  Overrode those fields with @JsonIgnore annotation like this:

@JsonInclude(Include.NON_NULL)
public class PKPassIgnoreNull extends PKPass {
    
    @JsonIgnore
    private List<PKBeacon> beacons;

    @JsonIgnore
    private List<PKLocation> locations;
}

However, it didn't help.  Is there any way to ignore the fields that are not required?

Thank you!

**Comment by drallgood** [comment]
Hmmm.  There may be a way, but the question is why?
Those fields don’t hurt anyone and since passes get zipped up anyway even the memory impact is negligible

**Comment by drallgood** [comment]
Actually I think we actually already ignore thanks values: jpasskit/src/main/java/de/brendamour/jpasskit/signing/PKAbstractSigningUtil.java

**Comment by mgkansal** [comment]
It's not ignoring null values. However, having extra empty array is still working for the iOS developer, they are not complaining yet.  So I believe, it should be okay.  Thanks for your response!
