### ISSUE TITLE
Can't add ticket to wallet but see on macbook

### ISSUE THREAD

**Issue by sascha-hack** [drallgood/jpasskit#369]
Hi,

cant add the ticket to my wallet on the iPhone.

I can watch the ticket on my MacBook but if I try to open/download it does not add it to the wallet.

Below is the pkpass. Has this something to do with the apple certificate? Which one do I need to add to the project?

https://sadeviollc.box.com/s/hzk2034zof1cwtvg28o5cgqgxden9mnc

**Comment by drallgood** [comment]
Hey @sascha-hack 
Sorry for the late reply.. it's been one of those weeks..

I've checked your pass with Apple's signpass util and it says it's valid.
However when I import it into my iPhone I get this in the device's console:
```
PKPass initWithData failed Error Domain=PKPassKitErrorDomain Code=1 "The pass cannot be read because it isn’t valid." UserInfo={NSLocalizedDescription=The pass cannot be read because it isn’t valid., NSUnderlyingError=0x13183ecc0 {Error Domain=PKPassKitErrorDomain Code=1 "The passTypeIdentifier or teamIdentifier provided may not match your certificate, or the certificate trust chain could not be verified." UserInfo={NSLocalizedDescription=The passTypeIdentifier or teamIdentifier provided may not match your certificate, or the certificate trust chain could not be verified.}}}
```

So either the teamIdentifier is incorrect or something is wrong with your certs

**Comment by drallgood** [comment]
As for your queestion regarding certificates:
Make sure you're using the correct AppleWWDRCA certificate.
Until Apple updates it (supposed to happen January 2022), the old one expiring in 2023 needs to be used for passes. See https://developer.apple.com/support/expiration/

Should be this one: https://developer.apple.com/certificationauthority/AppleWWDRCA.cer

**Comment by sascha-hack** [comment]
hi @drallgood 

the certificate was the problem. I used the wrong AppleWWDRCA. now it seems to work fine.

Thank you for your help.

How did you get log of adding a pass?

**Comment by drallgood** [comment]
@sascha-hack 
Here's how I do it. There might be other ways, though.

Connect your phone to your Mac.
Open the Console.app
Your iPhone should show up in the sidebar (if it doesn't, use Xcode to connect)
Select that. Then make sure to filter for "pass" or "passbook" (or something like that)
