### ISSUE TITLE
Log4j vulnerability

### ISSUE THREAD

**Issue by kinju4374** [drallgood/jpasskit#373]
Hi @drallgood ,

Do we need to check anything for log4j vulnerability in the project? Is there any update required from our side who are using this project locally?

**Comment by drallgood** [comment]
@kinju4374 Nope.
We only have a log4j v1.x test dependency via slf4j-log4j12
I have to check at some point why that is even needed. 
But it's only in test scope so wouldn't get shipped.
We use slf4j APIs only

**Comment by drallgood** [comment]
You can check it yourself by running `mvn dependency:tree | grep log4j`
