### ISSUE TITLE
Resource leak in the jpasskit.signing

### ISSUE THREAD

**Issue by gwago** [drallgood/jpasskit#389]
Hi,
there seems to be a resource leak in the de.brendamour.jpasskit.signing version 0.2.0
When signing many files in one go, we get "Too many open files" exception, and the process keeps many times resource files from the template directory opened.
I guess this is because of PKPassTemplateFolder.getAllFiles - the stream is not closed, but maybe I'm wrong.
I use openjdk version "1.8.0_232".
Many thanks in advance.

**Comment by drallgood** [comment]
That's totally possible.
I'll have a look

**Comment by gwago** [comment]
We fixed the leak by
      try {
        fis = new FileInputStream(file);
        byte[] byteArray = IOUtils.toByteArray(fis);
        String filePath = file.getCanonicalPath().substring(base.length() + 1);
        allFiles.put(filePath, ByteBuffer.wrap(byteArray));
      } finally {
        **IOUtils.closeQuietly(fis);**
      }

**Comment by drallgood** [comment]
Fixed. Thanks for the report @gwago
