### ISSUE TITLE
No longer possible to supply an empty list of PKDataDetectorType to suppress automatic data behaviour

### ISSUE THREAD

**Issue by iamthedevo** [drallgood/jpasskit#394]
As of 0.2.0, it is no longer possible to supply an empty list of PKDataDetectorType (PKFieldBuilder line 169) which I've previously used to prevent the wallet from trying to show a number as a telephone link.

Calling the builder with the following code, I would expect the pass.json field to have "dataDetectorTypes":[]
```
 .dataDetectorTypes(Collections.<PKDataDetectorType>emptyList()) // prevent from showing as a phone number etc
```

**Comment by drallgood** [comment]
Sounds like something we could enable again. I'll have a look

**Comment by drallgood** [comment]
Fixed. Thanks for the report @iamthedevo
