### ISSUE TITLE
Foreground color does not work if background image is set

### ISSUE THREAD

**Issue by malua** [drallgood/jpasskit#403]
Hey!

First of all, thanks for this great library!

I successfully added a background image, but as soon as I do that, the text color is automatically white. At least for the values of the lable-value pairs. Meaning the labels still have the chosen color, but the values are colored white.

I am not sure, if this is a limitation of passkit in general or if it maybe is a issue in this library.
Could you maybe help me rule that out? 

EDIT: I have read somewhere that stripColor is an undocumented property to control the text color of text above the strip image. maybe this would also change the color of the values above the backgroundImage. do you maybe have knowledge about that?

Thank you and all the best,
Lukas

**Comment by malua** [comment]
Nevermind, I have convinced people to use a different background image. One where the white text color is readable. :)

**Comment by spodaras** [comment]
Hello, I also have that issue and it can't be fixed by changing the image. Is there any chance to change the font color when using an image?
