### ISSUE TITLE
Test code uses certificates, which are available only locally

### ISSUE THREAD

**Issue by stepio** [drallgood/jpasskit#42]
Class de.brendamour.jpasskit.server.PKRestletServerResourceFactory contains constant path values for the certificates:
```java
	protected static final String APPLE_WWDRCA_CERT_PATH = "/Users/patrice/Documents/bitzeche/Projects/passkit/AppleWWDRCA.pem";
	protected static final String PKCS12_FILE_PATH = "/Users/patrice/Documents/bitzeche/Projects/passkit/Certificates.p12";
```
Why aren't these certificates available as test resources? Is it a bug or more like a known limitation?

**Comment by drallgood** [comment]
Oh... I probably never got around to cleaning this up. There are more local paths in this file than just the certificates.

Definitely a bug
