### ISSUE TITLE
missing parent pom on Maven Central Repository

### ISSUE THREAD

**Issue by sebphil** [drallgood/jpasskit#421]
When trying to update from 0.2.0 to 0.3.0 using maven, the build fails because the parent pom de.brendamour:jpasskit-parent can not be found, cf https://search.maven.org/search?q=g:de.brendamour%20AND%20a:jpasskit-parent%20AND%20v:0.3.0

**Comment by drallgood** [comment]
Thanks @sebphil for catching this 
I have to check what's needed to sync this too. Because it's deployed on sonatype

**Comment by drallgood** [comment]
Should be fixed now @sebphil
