### ISSUE TITLE
Version missing when trying to resolve

### ISSUE THREAD

**Issue by westlakem** [drallgood/jpasskit#422]
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for de.brendamour:jpasskit:jar is missing. @ line 20, column 17

**Comment by drallgood** [comment]
hey @westlakem 
I need some more info about this. What are you doing?
What's the full error?

This doesn't tell me much

**Comment by westlakem** [comment]
I found it was a typo in the version that I put for the dependency.  Please disregard.
