### ISSUE TITLE
Tutorial is outdated

### ISSUE THREAD

**Issue by trony2020** [drallgood/jpasskit#429]
Hello,

https://github.com/drallgood/jpasskit/blob/master/jpasskit/tutorial/mini-tutorial.txt

doesn't compile, I think it should be updated,
thanks.

**Comment by drallgood** [comment]
Thanks @trony2020 for catching this.

It might take me a few days/weeks to get around to this. Feel free to submit a PR if you have fixed it already :)

**Comment by a1764879** [comment]
PR https://github.com/drallgood/jpasskit/pull/467
