### ISSUE TITLE
cannot open created .pkpass with valid certs

### ISSUE THREAD

**Issue by userzee** [drallgood/jpasskit#433]
I am not able to open the apple pass (pkpass) file even signature and certificates are valid.
On verification it outputs as

Signature valid.
Certificates: (
	0: Apple Worldwide Developer Relations Certification Authority
	1: Pass Type ID: pass.com.card
)
Trust chain is valid.

*** SUCCEEDED ***

**Comment by drallgood** [comment]
Have you checked the device logs?
The certificate validation is not super helpful.

**Comment by userzee** [comment]
I am not able to check device logs, running simulator (iPhone 14 max pro, version 15.x.x).
I am new to xcode, tries viewing system logs for simulator, it shows nothing
I do not have clue on debugging pkpass file

**Comment by userzee** [comment]
I was using the wrong date label in pass.json. The correct date fixed the issue and finally, I was able to create pkpass successfully. THANKS
