### ISSUE TITLE
Getting this error = "java.lang.ClassCastException: org.bouncycastle.asn1.DERUnknownTag cannot be cast to org.bouncycastle.asn1.DERString"

### ISSUE THREAD

**Issue by Kavit900** [drallgood/jpasskit#44]
I have included the jar files of this project and other jar files like bouncy castle etc, now I created a EventExample.java file on my own, so that I could create an Event.pkpass file, but I getting this error, I am attaching a snapshot of the error.

![3](https://cloud.githubusercontent.com/assets/6806780/8855208/e4b2475a-3131-11e5-9efc-2deb889b2d90.png)

Also my EventExample.java code is here.Please take a look and help me out.

import java.awt.Color;
import java.nio.charset.Charset;
import java.util.ArrayList;

import de.brendamour.jpasskit.PKBarcode;
import de.brendamour.jpasskit.PKField;
import de.brendamour.jpasskit.PKPass;
import de.brendamour.jpasskit.enums.PKBarcodeFormat;
import de.brendamour.jpasskit.passes.PKStoreCard;
import de.brendamour.jpasskit.signing.PKSigningInformation;
import de.brendamour.jpasskit.signing.PKSigningUtil;

public class EventTicketExample {
	
	public static void main(String[] args) throws Throwable
	{
		PKPass pass = new PKPass();
		PKBarcode barcode = new PKBarcode();
		PKStoreCard storeCard = new PKStoreCard();
		ArrayList<PKField> primaryFields = new ArrayList<PKField>();

		PKField balanceField = new PKField();
		balanceField.setKey( "balance" );
		balanceField.setLabel( "balance" );
		balanceField.setValue( 20.0 );
		balanceField.setCurrencyCode( "EUR" );

		primaryFields.add( balanceField );

		barcode.setFormat( PKBarcodeFormat.PKBarcodeFormatQR );
		barcode.setMessage( "ABCDEFG" );
		barcode.setMessageEncoding( Charset.forName( "utf-8" ) );

		storeCard.setPrimaryFields( primaryFields );

		pass.setFormatVersion( 1 );
		pass.setPassTypeIdentifier( "pass.com.testetix.ticket" );
		pass.setSerialNumber( "000000002" );
		pass.setTeamIdentifier( "LSCA6RKZ57" );
		pass.setBarcode( barcode );
		pass.setOrganizationName( "Etix" );
		pass.setLogoText( "MyPass" );
		pass.setStoreCard( storeCard );
		pass.setDescription( "My PassBook" );
		pass.setBackgroundColorAsObject( Color.BLACK );
		//pass.setForegroundColor( "rgb(255,255,255 )" );
		
		String pkcs12KeyStoreFilePath = "/home/techie/etix/eclipse/eclipse_projects/Pass/resources/p12/PassbookCert.p12"; // This store the path for .p12 file path
		String keyStorePassword = ""; // This stores the password for the key file
		String appleWWDRCA = "/home/techie/etix/eclipse/eclipse_projects/Pass/resources/pem/WWDR.pem"; // This stores the WWDR certificate path
		
		String pathToTemplateDirectory = "/home/techie/etix/eclipse/eclipse_projects/Pass/resources/template"; // This stores the path to all the files that have to be zipped
		

	
		
		PKSigningInformation pkSigningInformation = PKSigningUtil.loadSigningInformationFromPKCS12FileAndIntermediateCertificateFile(
				pkcs12KeyStoreFilePath, keyStorePassword, appleWWDRCA);
		byte[] passZipAsByteArray = PKSigningUtil.createSignedAndZippedPkPassArchive(pass, pathToTemplateDirectory, pkSigningInformation);
	}

}

**Comment by Kavit900** [comment]
I debuged the code and I found error in this part of the program -  public static X509Certificate loadDERCertificate2(final InputStream certificateInputStream) throws IOException, CertificateException {
        try {
            CertificateFactory certificateFactory = CertificateFactory.getInstance("X.509", BouncyCastleProvider.PROVIDER_NAME);
            Certificate certificate = certificateFactory.generateCertificate(certificateInputStream);
            if (certificate instanceof X509Certificate) {
                return (X509Certificate) certificate;
            }
            throw new IOException("The key from the input stream could not be decrypted");
        } catch (IOException ex) {
            throw new IOException("The key from the input stream could not be decrypted", ex);
        } catch (NoSuchProviderException ex) {
            throw new IOException("The key from the input stream could not be decrypted", ex);
        }
    }



the line where error was pointed is = 
Certificate certificate = certificateFactory.generateCertificate(certificateInputStream);

**Comment by drallgood** [comment]
hmm....
Wrong format? Or it can't decrypt the p12 file...

**Comment by drallgood** [comment]
No response. Closed.

**Comment by mparbhin** [comment]
I am also facing the same issue. @Kavit900 how were you able to resolve the issue?
