### ISSUE TITLE
passbook pass is not opening in iphone but pass format is correct

### ISSUE THREAD

**Issue by nitinguptaindore** [drallgood/jpasskit#45]
i am sending pass through email but passbook pass is not opening in iphone. when i click on .pkpass file it is not opening and not giving any error.
pass opens in android passwallet app and apple mac system also
![img_2724](https://cloud.githubusercontent.com/assets/7198321/8869678/248d32fe-3204-11e5-8594-300cad751ce8.PNG)

**Comment by nitinguptaindore** [comment]
any one plz help me to solve this problem

**Comment by alvinbaena** [comment]
If you are sending the mail through exchange the pkpass gets decompressed and scanned for viruses, then recompressed and sent. This damages the pkpass because it has to be compressed using the certificate.

It may be an issue with the mail client, not the library.

**Comment by drallgood** [comment]
Decompressing and compressing it again shouldn't be an issue.
And Virus scanners usually just decompress to check but don't actually touch the attachment.

**Comment by alvinbaena** [comment]
Hmmm, then I don't know, we had an issue exactly like this and it happened when distributing pkpasses using exchange.

**Comment by drallgood** [comment]
hmm weird...
Maybe it broke the zip or changed the content somehow. The .pkpass is just a ZIP file with signed content. Nothing special to it....

**Comment by drallgood** [comment]
Is this solved?

**Comment by T4ut0** [comment]
Hey, I am having the same issue again with my iOS device. Is there any solution to fix this problem? Thanks.
