### ISSUE TITLE
AppleWWDRCA.cer is expired, what certificate now?

### ISSUE THREAD

**Issue by sascha-hack** [drallgood/jpasskit#456]
Hi since AppleWWDRCA.cer is now expired it does not work to sign the pass.

It did say something that we should use now AppleWWDRCAG4.cer but it appears to now work.

Any idea? I will try to see what the logs are saying

**Comment by drallgood** [comment]
@sascha-hack Good question... it's been a bit of a mess on Apple's side. 
I have to hunt down the page where they have documented the whole process.. maybe it's been updated to tell us which cert they require now.
You can't just use a random one of the certs Apple has.. it has to be the correct one

**Comment by drallgood** [comment]
Found it: https://developer.apple.com/support/expiration/

Supposedly you need the G4 cert... but you said that aint working 🤔

**Comment by sascha-hack** [comment]
I found something but not to sure what that means.
on the mac it seems to build correctly and I can open the pass. But on the server I am getting following exception.
Not to sure what that means or how to debug this?
de.brendamour.jpasskit.signing.PKSigningException: Error when signing manifest I use 0.1.2
