### ISSUE TITLE
Check certificate expiration

### ISSUE THREAD

**Issue by woolfel** [drallgood/jpasskit#46]
I was reading the code and noticed PKSigningUtil doesn't check certificate expiration by calling X509Certificate.checkValidity(). I also looked at bouncy castle's provider to see if they check the validity after the file is read into memory.

It might be a good idea to check for expiration. I'm happy to contribute a patch. One thought was to add a boolean parameter to loadSigningInformationFromPKCS12FileAndIntermediateCertificateFile method. Something like boolean checkValidity. If it's true, the method would call the method. Calling X509Certificate.checkValidity() would throw an exception if it is expired, so not every would want that.

**Comment by stepio** [comment]
Nice idea! If a pass is signed with an expired certificate, it's rejected by Passbook on iPhone. So throwing an exception on the server side will inform the service owner about the issue.

**Comment by woolfel** [comment]
I also noticed the appleWWDRCA expires in 2016, so it would be good to throw an exception. I can see someone forgetting to update both certificates on their server and then wonder "why isn't my pass working anymore?"

**Comment by drallgood** [comment]
I'm not sure that's true.
If I remember Apple's documentation correctly, passes with expired certificates are still supposed to work...

Otherwise you'd need to reissue passes every year or so...

Could you please verify that's the case?

**Comment by woolfel** [comment]
a co-worker checked the official docs. here is what it states:

•	Pass Type ID Certificate (Passbook)
If your certificate expires, passes that are already installed on users' devices will continue to function normally. However, you will no longer be able to sign new passes or send updates to existing passes. If your certificate has been revoked, your passes will no longer function properly."

hopefully I'm interpreting that correctly. Revoke to me means the current date isn't between start and end date of the certificate, but I could be wrong.

**Comment by drallgood** [comment]
Revoked means Apple has revoked it (or you did so in the certificates portal)

**Comment by woolfel** [comment]
ok. it also says in the previous sentence "However, you will no longer be able to sign new passes or send updates to existing passes" with an expired cert

**Comment by stepio** [comment]
I have not checked recently, but as per my experience, behavior is the next one:
 - already added pass (added when the certificate haven't been expired yet), works fine - they're displayed well with "the pass is expired" message;
- attempt to add a previously expired pass fails - such a pass is rejected with "No Pass Available for This Code" message in Passbook app:
https://goo.gl/t9tto8

**Comment by drallgood** [comment]
Yep. So it makes sense to check for expiration...
I'd even say that we should always check, because it just doesn't make any sense to create broken passes.

**Comment by woolfel** [comment]
ok, I'll make the change tonight and create a pull request. thanks for responding so quickly.
