### ISSUE TITLE
Missing release of jpasskit-parent on Maven Central

### ISSUE THREAD

**Issue by sebphil** [drallgood/jpasskit#473]
Hi ! Maven Central has the new version 0.3.1 for jpasskit and jpasskit-server, but both of them reference jpasskit-parent:0.3.1 which is not present. This makes the upgrade to the new version fail. cf https://central.sonatype.com/search?q=de.brendamour

Can you please release jpasskit-parent:0.3.1 on Maven Central?

edit: This happened already last year, see #421. Perhaps is there something missing from your release workflow?

**Comment by drallgood** [comment]
Huh. Weird. I thought I had fixed that already last year. 
Thanks for reporting this @sebphil 

let me see how i can fix that

**Comment by drallgood** [comment]
I think I did it.. phew..
Had to do a new release 0.3.2 and even then it took like 10 attempts because stuff would always time out on the nexus side.

**Comment by sebphil** [comment]
Thanks for the new release!
