### ISSUE TITLE
Using .p8 certificate

### ISSUE THREAD

**Issue by vincedprime** [drallgood/jpasskit#482]
Is it possible to sign it with a .p8 certificate instead of .p12? If so please guide

Thanks

**Comment by vincedprime** [comment]
Also can I user .cer format instead of .pem?

**Comment by drallgood** [comment]
Gonna close this as I hope I answered this :)

**Comment by vincedprime** [comment]
Thank you for the update. Can you provide me a basic idea of what I should be doing in my custom signer utility? The library utility loads a PKCS12 file and an intermediate certificate, performs necessary operations on the loaded data, and returns the resulting signing information.

Sry for asking basic questions as I'm new to the library and having a tough time wrapping my head around it
