### ISSUE TITLE
Support for NFC

### ISSUE THREAD

**Issue by woolfel** [drallgood/jpasskit#49]
Is there any plans to support NFC in future releases? The project I am on might need it in the future, so I'm willing to contribute to the feature.

thanks

**Comment by woolfel** [comment]
Just a couple of quick notes. NFC is a new feature for iOS 9, so there isn't any immediate demand. Not like you can actually use it today and definitely not with an older iPhone.

**Comment by stepio** [comment]
Hi Peter,

If you're talking about new Passbook (Wallet) features from iOS9, than yes - in my opinion they should be implemented. But as I know, the updated specs are not released yet, so we should wait a bit.

**Comment by drallgood** [comment]
???
I haven't noticed any changes...

The passbook package hasn't changed since 2013: https://developer.apple.com/library/prerelease/ios/documentation/UserExperience/Reference/PassKit_Bundle/RevisionHistory.html#//apple_ref/doc/uid/TP40012026-CH99-SW1)

And neither has the web service:
https://developer.apple.com/library/prerelease/ios/documentation/PassKit/Reference/PassKit_WebService/RevisionHistory.html#//apple_ref/doc/uid/TP40011988-CH99-SW1

**Comment by stepio** [comment]
I saw the keynote about Wallet (which is the new name for Passbook) in iOS9 and the changes would be - at least a couple of new fields in JSON are expected.

But yes, it's not documented yet.

**Comment by woolfel** [comment]
others have already responded. It's a new feature in iOS9. The final docs aren't available yet. Once the final Passbook wallet feature is finalized, I'm happy to contribute that to the project.

**Comment by drallgood** [comment]
Apple has released the documentation and as far as I could see, everything should be working.
Has anyone tested this?

**Comment by woolfel** [comment]
I tested it based on the details Apple showed at wwdc, but I didn't look at the official docs. I'll take a look and see if there are any changes.

**Comment by woolfel** [comment]
anyone have the link handy? I couldn't find it at developer.apple.com/passbook

**Comment by drallgood** [comment]
https://developer.apple.com/library/prerelease/ios/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/Introduction.html#//apple_ref/doc/uid/TP40012026

I've already implemented the changes (if I didn't miss anything)

**Comment by woolfel** [comment]
Looking at the short blurb on the official page, I don't see any changes from what was shown at WWDC. others on the project have used iOS9 beta to test it, but I don't have an iPhone 6 to test the nfc on a real device. Here's the actual text from apple's website.

NFC Dictionary Keys

Information about the NFC payload passed to an Apple Pay terminal.

Key name
Type
Description

message
string
Required. The payload to be transmitted to the Apple Pay terminal. Must be 64 bytes or less. Messages longer than 64 bytes are truncated by the system.

encryptionPublicKey
string
Optional. The public encryption key used by the Value Added Services protocol. Use a Base64 encoded X.509 SubjectPublicKeyInfo structure containing a ECDH public key for group P256.

**Comment by drallgood** [comment]
I'm closing this. Guess it's working

**Comment by woolfel** [comment]
it works fine on our testing... good to close
