### ISSUE TITLE
Dropping Java 8 support

### ISSUE THREAD

**Issue by drallgood** [drallgood/jpasskit#495]
I think it's time to drop Java 8 support.
More and more dependencies are doing so, so I think it's time.

Opinions?

**Comment by AlBundy33** [comment]
do you need features from newer versions?
I'm more a fan of being compatible as much and as long as possible.
But this is maybe only personal preference. 😃

**Comment by drallgood** [comment]
@AlBundy33 I agree which is why I kept it on 8 for so long. 
Unfortunately it's becoming more and more difficult because dependencies are dropping support. And staying on older versions can only last so long 

Hence the question 😊

**Comment by AlBundy33** [comment]
if maintaining the lib gets more difficult them maybe it's time so move to java 11 (next LTS after java 8) 🤔
