### ISSUE TITLE
Replace ToStringBuilder.reflectionToString with rzwitserloot/lombok

### ISSUE THREAD

**Issue by stepio** [drallgood/jpasskit#50]
Hello, guys,

Recently I've tried http://projectlombok.org/ and loved it.
Maybe we should use it instead of ToStringBuilder.reflectionToString ?

Reflection is slow but "reflectionToString" is easy. Lombok uses best from both worlds: no need to write your own implementation, just annotate the class and the lib enriches your bytecode.

Example is here:
http://jnb.ociweb.com/jnb/jnbJan2010.html#tostring

P.S.: I only use it for overriding the existing methods - do not like the idea of using specific plugins for IDE to fix the code highlighting.

**Comment by drallgood** [comment]
hmm.. not sure I like this approach...
The whole thing looks messy to me.
