### ISSUE TITLE
FileNotFoundException in rest.ssl.keystore.path

### ISSUE THREAD

**Issue by MohammedAlsuliman** [drallgood/jpasskit#503]
**Hello there,**

When i'm trying to run my application on a jar file, I don't know what should i add in rest.ssl.keystore.path, 

In localhost when i tried: 
`serverConfigurationProperties.put("rest.ssl.keystore.path", "src/main/resources/Certificates.p12");`
It's working just fine, but when i build the jar I don't know what should i put in the path, 

I tried the following:
`serverConfigurationProperties.put("rest.ssl.keystore.path", "/backend-0.0.1-exec.jar/BOOT-INF/classes/Certificates.p12");`
But i had no luck,

**Could you guide me on this?
Thanks.**

**Comment by drallgood** [comment]
@MohammedAlsuliman Sorry for the late response. I somehow must have missed it.
Were you able to solve it ultimately?
