### ISSUE TITLE
I have a pkpass that doesn't open

### ISSUE THREAD

**Issue by costispavlou** [drallgood/jpasskit#505]
Hi, dunno if you can help me but I got this pkpass i want to add on my wallet but it seems the certificate has expired so when I email it to myself or try opening it from my iphone it doesn't open. Just shows the icon. 
I can zip open it and see all the information there, and also validated it:
![image](https://github.com/drallgood/jpasskit/assets/57916603/1aa8eafc-33a0-4c02-aea0-f135847b4283)
any chance you can help? I can provide the pkpass if needed

**Comment by drallgood** [comment]
@costispavlou Sorry for the late reply. I forgot about this one. 

Were you able to figure it out on your own?

**Comment by costispavlou** [comment]
> @costispavlou Sorry for the late reply. I forgot about this one.
> 
> Were you able to figure it out on your own?

hey @drallgood, thanks for the reply. no i havent.. and nothing works. Was wondering if you can help me ?
I can provide you with the pass.

**Comment by drallgood** [comment]
@costispavlou For one it looks like you're not using the correct WWDR certificate. Make sure you download the correct one from Apple https://www.apple.com/certificateauthority/

**Comment by costispavlou** [comment]
can i attach it so you can do it for me? i've literally have no idea how to sign or use certificates. I just want to use this pass and the authority that made it didn't use the right stuff afaik.

**Comment by drallgood** [comment]
@costispavlou Sorry no. I don't have much time currently.
