### ISSUE TITLE
Foreground color does not work if background image is set

### ISSUE THREAD

**Issue by spodaras** [drallgood/jpasskit#509]
Hello,

as soon as I use a strip image in the background, the font color changes to white. Any chance that I set tge color back to black?
Changing the image is no option for me. The same issue was already reported here:

https://github.com/drallgood/jpasskit/issues/403

**Comment by drallgood** [comment]
@spodaras I would assume that is something Apple has implemented on their end and we cannot change. 
This project merely allows you to configure the PKPass structure according to Apple's specifications but is not responsible for how they get displayed on different platforms (I have myself many bugs open with Apple for things that do not work reliably across their platforms)

**Comment by drallgood** [comment]
I will close this for now. If you discover there's indeed an issue with how this tool creates the JSON structures, feel free to reopen it

**Comment by spodaras** [comment]
Hello @drallgood, did you ever try to add the parameter "stripColor" as suggested here? It's an undocumented paramter, though. https://stackoverflow.com/questions/22580405/labelcolor-not-responding-in-passbook-coupon-type-pass

**Comment by drallgood** [comment]
We do not support undocumented APIs as they might break at any time

**Comment by spodaras** [comment]
Fair enough, thank you
