### ISSUE TITLE
upgrade bouncy castle

### ISSUE THREAD

**Issue by woolfel** [drallgood/jpasskit#51]
Are there any plans to upgrade bouncy castle to jdk16 1.46 ?
http://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk16/1.46

I'm seeing jar collisions in weblogic 12c, since it uses bcprov-jdk16 instead of 15. I tried to force weblogic to use 15 with prefer-application-packages configuration in weblogic.xml, but that doesn't get around the issue. Has anyone successfully used jpasskit on weblogic 12c?

**Comment by woolfel** [comment]
I dug deep into this weird weblogic 12 issue. It appears that bcprov-jdk16 isn't an official bouncy castle release and bcpkix-jdk15on is the most current official release. That makes me ask, why does maven central have this version http://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk16/1.46. What is going on here? Is maven doing something crazy and stupid? Why is oracle weblogic using a version that isn't an official release?

**Comment by woolfel** [comment]
a bit more info in case other people come across this problem. the bouncy castle issue appears to be specific to OSX and how security is setup for the user. on windows with weblogic 12c I don't see the issue.

**Comment by drallgood** [comment]
This is indeed weird.
Thanks for looking into it :smile:
