### ISSUE TITLE
Create multiple passes at once

### ISSUE THREAD

**Issue by schube** [drallgood/jpasskit#521]
Hello!

Thank you for your great library!
I wonder if / how it is possible, to create **multiple passes** at once/in one pkpass-file.

For example, if I want to create 4 tickets for a junior soccer game, I want the user to download one pkpass which contains all 4 tickets with 4 different seats.

Since the `PKFileBasedSigningUtil::createSignedAndZippedPkPassArchive` method accepts only one pass and not an array/list of passes, I guess it is not possible. 
Or is there a way? 

Thank you,
Bernhard

**Comment by drallgood** [comment]
Unfortunately that's not possible. A pass is a single entity and you can't bundle them together like you suggested. 
A pkpass file always represents one single pass and is rendered that way. 

Of course you can create a single pass that logically represents 4 tickets, e.g by writing "4 Tickets" on it. But it's always gonna show as a single pass. 

See also https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html#//apple_ref/doc/uid/TP40012195-CH4-SW1

**Comment by schube** [comment]
I understand, thank you for clarification!
And once again, thank you for your wonderful library!

**Comment by jakubkrolikowski** [comment]
Hi, actually there is an official way to bundle passes in Apple documentation:

[Create a bundle of passes](https://developer.apple.com/documentation/walletpasses/distributing_and_updating_a_pass#3793284)

Would you consider to implement ..pkpasses creation?

**Comment by drallgood** [comment]
@jakubkrolikowski  Must be new.

Anyhow.. I don't see that it would bring any benefits to do so.
Anybody can generate a zip file. No need for the lib to do this.

Unless you can find a valid reason why it would be beneficial?
