### ISSUE TITLE
PKPassTemplateFolder - unable to load template path from .jar file

### ISSUE THREAD

**Issue by nefiko** [drallgood/jpasskit#524]
Hello,

The PKPassTemplateFolder class has two constructors, one requiring a URL and one requiring a String of the path to the template directory. I have some images and icons in my template folder.

After building and deploying my project, my data is written into a .jar file from where I get my resources, including the icons in my directory folder. But in a .jar file, you can't access file paths directly, you can only get their corresponding InputStreams, so I can't create a PKPassTemplateFolder without getting a FileNotFoundException. loadSigningInformationFromPKCS12AndIntermediateCertificate in contrast accepts an InputStream, which is why I don't have a problem creating a PKSigningInformation object.

Are there any workarounds this problem or do you have any advice on how to solve it?

**Comment by drallgood** [comment]
@nefiko 
Have a look at [jpasskit/src/main/java/de/brendamour/jpasskit/signing/PKPassTemplateInMemory.java](https://github.com/drallgood/jpasskit/src/main/java/de/brendamour/jpasskit/signing/PKPassTemplateInMemory.java) 
Alternatively you can always provide your own implementation of [jpasskit/src/main/java/de/brendamour/jpasskit/signing/IPKPassTemplate.java](https://github.com/drallgood/jpasskit/blob/master/jpasskit/src/main/java/de/brendamour/jpasskit/signing/IPKPassTemplate.java)

Hope that helps
