### ISSUE TITLE
jPasskit not available in Maven Central

### ISSUE THREAD

**Issue by RommelTJ** [drallgood/jpasskit#53]
When I search for it in Maven Central it is not found.

**Comment by drallgood** [comment]
I haven't published a release, yet. But the snapshot is available here:
https://oss.sonatype.org/content/repositories/snapshots/de/brendamour/jpasskit/

Maybe I should just release the current version

**Comment by RommelTJ** [comment]
Perfect. Thank you! 
I was about to implement the Apple Passbook Web Service API from scratch and I strolled upon your project. Seems like a good solution to me!

I was in the process of installing jPasskit locally from source. I'll use the snapshot that you indicate if you don't wish to release the current version yet.

**Comment by drallgood** [comment]
Great. I'm glad this is useful to you :)

Give me a few minutes to prepare the release. I've never done this to maven central, so no idea how long it will take...

**Comment by RommelTJ** [comment]
I was able to get the SNAPSHOT releases installed. Thanks so much! I had to edit my ~/.m2/settings.xml. We can close the issue if you'd like. Looking forward to playing with jPasskit! :sunglasses:

**Comment by drallgood** [comment]
I've pushed 0.0.7 to Sonatype wich should sync to central.
We'll see how long that takes :)
