### ISSUE TITLE
UnsupportedClassVersionError (Unable to load class)

### ISSUE THREAD

**Issue by RommelTJ** [drallgood/jpasskit#54]
Does this project have any dependencies that I need to be aware of? I am attempting to use jPasskit (server) on an existing Jersey webapp. When I try to run it, I get this error about not being able to load PKDeviceResource: 

```
java.lang.UnsupportedClassVersionError: org/restlet/resource/ServerResource : Unsupported major.minor version 51.0 (unable to load class org.restlet.resource.ServerResource) (unable to load class de.brendamour.jpasskit.server.PKDeviceResource)
[...]
```
I am running JDK 1.6:
java version "1.6.0_30"
OpenJDK Runtime Environment (IcedTea6 1.13.1) (rhel-3.1.13.1.el6_5-x86_64)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)

I added the following dependencies: 
```
                <dependency>
			<groupId>de.brendamour</groupId>
			<artifactId>jpasskit</artifactId>
			<version>0.0.7-SNAPSHOT</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>de.brendamour</groupId>
			<artifactId>jpasskit.server</artifactId>
			<version>0.0.2-SNAPSHOT</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.restlet.jee</groupId>
			<artifactId>org.restlet</artifactId>
			<version>2.3.4</version>
			<scope>compile</scope>
		</dependency>
```

Any ideas?

**Comment by drallgood** [comment]
Not a dependency, but you should be using Java 1.8.

**Comment by drallgood** [comment]
I think I still compile it against 1.6, but nobody should be using such an old version anymore.

**Comment by RommelTJ** [comment]
I installed OpenJDK 1.8 and compiled against it and it's working fine now. Thanks again, friend!
