### ISSUE TITLE
About PKPass and pass.json

### ISSUE THREAD

**Issue by CokeCola313** [drallgood/jpasskit#546]
I need to generate json in a different format than PKPass and the file name is also different
The rest are roughly the same as the steps for this jpasskit to generate zip
I will PKFileBasedSigningUtil, PKAbstractSigningUtil, IPKSigningUtil
Copy it to my project and modify the PKPass to the class I need.
Modify sha1 in PKFileBasedSigningUtil.createManifestJSONFile to sha256
Everything is working fine but is there anything I can do better than copying the extension into my project modification?

**Comment by drallgood** [comment]
Not really. This is not an intended use case for jPasskit

**Comment by drallgood** [comment]
Good luck with your project 😊

**Comment by CokeCola313** [comment]
> 並不真地。這不是 jPasskit 的預期用例

Apple Wallet Order requires the same process
Would you consider adding this feature? Just replace the PKPass class with the Order class and let it generate order.json

**Comment by CokeCola313** [comment]
> > 並不真地。這不是 jPasskit 的預期用例
> 
> Apple Wallet Order requires the same process Would you consider adding this feature? Just replace the PKPass class with the Order class and let it generate order.json

Or do you have any suggestions? Thank you

**Comment by drallgood** [comment]
Do you have any documentation for that?

yes, that might be possible. Depending on how similar things are

**Comment by CokeCola313** [comment]
> 你有這方面的文件嗎？
> 
> 是的，這也許是可能的。取決於事物的相似程度

https://developer.apple.com/documentation/walletorders/order

This is the Apple wallet order document
Just need to be able to pass in the first parameter of IPKSigningUtil.createSignedAndZippedPkPassArchive PKPass -> Order
As far as I know there are one or two duplicate fields
And change the file name in PKFileBasedSigningUtil.createPassJSONFile to order.json
Hashing.sha1() -> Hashing.sha256 in PKFileBasedSigningUtil.createManifestJSONFile
Then it can run well to generate Apple wallet orders.

**Comment by CH-TamVo** [comment]
I need to generate bundle PKPass at the same time. would you please share me some sample codes thanks

**Comment by drallgood** [comment]
TBH, that looks like a completely different structure than a pass. 
So no, I don't think it makes sense to include this here.
