### ISSUE TITLE
Unable to parse Field value as a date. 

### ISSUE THREAD

**Issue by mavriksc** [drallgood/jpasskit#56]
All of my fields are just text, and the values are null that imply a date. 

 We expect dates in "W3C date time stamp format", either "Complete date plus hours and minutes" or "Complete date plus hours, minutes and seconds". For example, 1980-05-07T10:30-05:00.

![pass](https://cloud.githubusercontent.com/assets/2230755/10678348/68a004de-78d7-11e5-9a4b-9adf10d3953e.PNG)

**Comment by mavriksc** [comment]
"solved" the issue 
	PKField field = new PKField(PARAM_AGENCY_NAME, "Agency", req.getParameter(PARAM_AGENCY_NAME));
		field.setIsRelative(null);
		passRequest.getHeaderFields().add(field);
instead of just 
passRequest.getHeaderFields().add( new PKField(PARAM_AGENCY_NAME, "Agency", req.getParameter(PARAM_AGENCY_NAME)));

**Comment by drallgood** [comment]
hmm.. I don't get what you're trying to do and what isn't working.

Can you explain this in a little bit more detail?  What are you doing? What's happening and what's the expected outcome?

**Comment by mavriksc** [comment]
Sorry if i was short. was getting frustrated, but i do appreciate the library and assistance. 
i was creating a field and adding it to a List<PKField>  adding that to an event ticket and that to a pass. 
when loading the pass on MAC it came up fine, but when loading it on iPhone it could fail to download. 

from the phone log:
 Invalid data error reading pass pass.com.foo.testpass/1234567. Unable to parse eventName Blah blah blah as a date. We expect dates in "W3C date time stamp format", either "Complete date plus hours and minutes" or "Complete date plus hours, minutes and seconds". For example, 1980-05-07T10:30-05:00.

but if i instead create the field then setIsRelative(null) then add it to the list. i do not get the error. 


maybe have different constructors for text, currency, and date field types. 
Thank you.

**Comment by drallgood** [comment]
Ah. I guess it's interpreting it as a date because isRelative is set.
That shouldn't happen. In fact, I don't know how this is even possible since the default value for this field is null.
Are you using the latest version of jpasskit?

**Comment by mavriksc** [comment]
for some reason it showed 0.0.9 is that possible? changed ivy to 0.0.7 and now  PKField(String,String,String) constructor is not an option, is that right?

**Comment by drallgood** [comment]
Nope. 0.0.7 is the latest release version.
Maybe you were using a fork or something...

**Comment by drallgood** [comment]
PKField now has the mentioned constructor, btw :smile:
