### ISSUE TITLE
Is it possible to set a message when using PKSendPushNotificationUtil.java

### ISSUE THREAD

**Issue by eblangga** [drallgood/jpasskit#567]
I am currently using the JPasskit to generate passes, and I want to send them an update message with json format. but somehow the message in the function of `PKSendPushNotificationUtil.sendPushNotificationAsync` is set to `EMPTY_PUSH_JSON_STRING`. If I am reading the code correctly this would be where the update message should be set right? Please help me if I am misunderstanding anything for my current implementation

**Comment by drallgood** [comment]
Hey @eblangga 
Not quite. How this works is that you send a push notification to the device (using the push token that was registered for a particular device and pass) and then the device will fetch a new version from the server. 
So it does require the web service API to be deployed. 

There is no way to send a pass update over APNS. It's not designed for bigger payloads as those push notifications are supposed to still work even if you have a really poor connection. 
(remember, they were invented back in the olden days of 2G and 3G!)
