### ISSUE TITLE
passbook pass is not opening in iphone

### ISSUE THREAD

**Issue by jalinares** [drallgood/jpasskit#59]
I'm testing the version 0.0.7 and 0.0.6. the test (switching path), especially this class PKSigningUtilTest the method testJson. You have successfully generated the pass.pkpass file, but when I try to open iPhone does not open, This using certificates found in test / java / resources / passbook, I could tell what would be the way to fix it, if issue certificates? Thank you

**Comment by drallgood** [comment]
@jalinares 
The certificates included in the project aren't valid and can't be used to create/deploy valid passes to an iPhone. This is a safety measure so nobody can use my credentials to create passes.

You'll need to create and import your own certificates and keys to get this working. See https://github.com/drallgood/jpasskit/blob/master/jpasskit/tutorial/mini-tutorial.txt or Apple's documentation.
