### ISSUE TITLE
Add warning when generating PKField with currencyCode

### ISSUE THREAD

**Issue by royrwood** [drallgood/jpasskit#599]
I had a problem recently when I was adding a PKField and I set the value as a String and also set the currencyCode.  Apparently iOS silently rejects passkits with inconsistent field data, which led to a lot of frustration on my part.  Once I changed the value to a BigDecimal, all was well again.

I humbly request that some logic be added to the PKField builder to watch for cases like that.  Apple doesn't seem to explicitly indicate that it validates the passkit.json fields in this way, but iOS clearly does so.  I'm not sure what other combinations of fields and types cause trouble, but I know that String + currencyCode leads to silent rejection of the passkit by iOS.

Sample bad code:

```
        String currentBalance = "100.00";
        String currencyCode = "USD";
        PKField balanceField = PKField.builder()
            .key("balance")
            .label("_balance")
            .value(currentBalance)
            .currencyCode(currencyCode)
            .build();
```

**Comment by drallgood** [comment]
Hey @royrwood 
Thank you for this report

I think we even have this already:

https://github.com/drallgood/jpasskit/blob/master/jpasskit/src/main/java/de/brendamour/jpasskit/PKFieldBuilder.java#L213

So all you would have to do is use the validation logic we provide using the 'isValid()' builder method 

You can do this on any level, field or even pass level

Hope that solves your issue?

**Comment by royrwood** [comment]
Wow, that's great!  I did not know about that method.  I'm adding that to my code now...

**Comment by royrwood** [comment]
Ooh-- and there is a method to get the validation errors in human-readable form: getValidationErrors( )

**Comment by drallgood** [comment]
yep!

I probably had the exact same issue you had so I added some validation 😂

**Comment by royrwood** [comment]
That all works great.  Thanks for the quick responses!

A final suggestion would be to include a reference to the mini tutorial in the main README.  It's really helpful, and I didn't realize it was there.  The mini-tutorial should also use the getValidationErrors( ) method, since it's FANTASTIC.

Thanks for all the work on this!!!!!

**Comment by drallgood** [comment]
Glad you're enjoying it 😉
Feel ffree to submit a PR with improvements 😊
