### ISSUE TITLE
In memory templates in stable release

### ISSUE THREAD

**Issue by agruttner** [drallgood/jpasskit#60]
Hi there,

Thanks for putting this library together! Do you have an ETA of when the in memory templates feature will make it to a stable release? Really looking forward to using them!

Cheers

**Comment by drallgood** [comment]
@agruttner 
To be honest, I'm just waiting for some feedback, whether everything is working as expected.
Other than that, I could release it immediately :smile:

**Comment by agruttner** [comment]
Sounds great, thanks for your quick reply!

**Comment by agruttner** [comment]
Hi, any updates on this?

**Comment by drallgood** [comment]
I'm probably going to release it tomorrow. Just need to find some time to do it ^^

**Comment by drallgood** [comment]
Released
