### ISSUE TITLE
Build against java 7

### ISSUE THREAD

**Issue by agruttner** [drallgood/jpasskit#61]
Hi,

I'm trying to develop against your unstable release and noticed that you have your build target set to java 1.8. Building against java 1.7 would allow more projects to use your library and it doesn't seem that you are using any features that are java 8 specific.

We're stuck on java 7 for other reasons so we would really appreciate this.

Thanks again for writing this library!

**Comment by drallgood** [comment]
Hi @agruttner 
To be honest, I really want to switch the codebase to Java 8. You're right, there's nothing in there yet that needs it, but that will probably change soon.

If you don't need the latest changes, you could use the latest stable version (0.0.7).
To be honest.. I'm a little on the fence here. Maybe I could keep it on 1.7 until I start refactoring...

**Comment by drallgood** [comment]
Using 1.7 for now... 
Just be aware that this will change soon!
