### ISSUE TITLE
Boarding Pass

### ISSUE THREAD

**Issue by jalinares** [drallgood/jpasskit#64]
I'm using the version 0.0.7, I am implementing a boarding Pass and I see the option to add Footer, I also see that Apple allows to the boarding pass several secundary fields and the same for auxiliary fields, and add this? This is the Apple page that explains the different passbook
https://developer.apple.com/library/watchos/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html#//apple_ref/doc/uid/TP40012195-CH4-SW8

**Comment by drallgood** [comment]
Hey @jalinares 
I'm not sure I understand your question. Yes, you can add secondary and auxiliary fields to your pass when using jPasskit. Just use the provided methods.

**Comment by jalinares** [comment]
Yes, I can add secondary and auxiliary fields as you indicate,
protected List <PKField> secondaryFields;
protected List <PKField> auxiliaryFields;.

But you can not add a new secondaryFields or auxiliaryFields as shown in Apple's documentation.

The footer field is missing.

**Comment by drallgood** [comment]
Aaah... I think I get what you're saying. 
The footer is not a field but an image. That one is indeed missing in my template classes, but other than that, you can just add it to your template and it would be fine. 

What you, however, cannot do, is adding fields to that area. There is no "footer" field in the passkit package format:
https://developer.apple.com/library/ios/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/LowerLevel.html#//apple_ref/doc/uid/TP40012026-CH3-SW1

**Comment by jalinares** [comment]
OK, thanks
