### ISSUE TITLE
barcode on iPhone 4S and Android

### ISSUE THREAD

**Issue by jalinares** [drallgood/jpasskit#66]
The barcode on android and iphone 4s are not'm usabdo a QR, this is the code that generates me:

PKPass pass = new PKPass();
PKBarcode barcode = new PKBarcode();

barcode.setFormat(PKBarcodeFormat.PKBarcodeFormatQR);
barcode.setMessage("0006127418");
barcode.setMessageEncoding(Charset.forName("UTF-8"));
barcode.setAltText("0006127418");
pass.setBarcodes(Arrays.asList(barcode));

"barcodes": [
     {
       "format", "PKBarcodeFormatQR"
       "altText": "0006127418"
       "message": "0006127418"
       "messageEncoding": "UTF-8"
     }
   ],

Tested on iPhone 4S (ios 8) and Android (4.1.2) and the barcode is not seen.

Tested on iPhone 5, 5s, 6 and is right with ios 9

I'm using version 0.0.7

**Comment by stepio** [comment]
Hi,

It's a known limitation - iOS versions before 9 does not know about "barcodes" field.
So you should set both "barcodes" (new) and "barcode" (legacy).

**Comment by jalinares** [comment]
OK, thanks
