### ISSUE TITLE
Plugin "org.apache.maven.plugins:maven-surefire-report-plugin:2.5" not found

### ISSUE THREAD

**Issue by stepio** [drallgood/jpasskit#68]
Plugin "org.apache.maven.plugins:maven-surefire-report-plugin:2.5" not found here:
http://trac.bitzeche.de/archiva/repository/mirror/org/apache/maven/plugins/maven-surefire-report-plugin/2.5/

For some reason your mirror failed to cache a valid version of this plugin.

**Comment by stepio** [comment]
It's a minor bug - no affect on the build, just an annoying error in "pom.xml" structure.

**Comment by drallgood** [comment]
I will investigate this. Thanks for the report!

**Comment by drallgood** [comment]
Seems to be working
