### ISSUE TITLE
java.security.cert.CertificateException: X.509 not found

### ISSUE THREAD

**Issue by mitesh51** [drallgood/jpasskit#69]
CertificateFactory certificateFactory = CertificateFactory.getInstance("X.509", BouncyCastleProvider.PROVIDER_NAME); gives java.security.cert.CertificateException: X.509 not found while we deploy it on Azure Web App. But the same thing works on local machine. We also checked that the provider is getting added through logs but somehow its not able to get instance in the above code. 

Not sure if this is the right place to raise it but couldn't find similar issue elsewhere so raising it here.

**Comment by drallgood** [comment]
Hmm that is indeed weird. To be honest, I have no idea why that might happen.

Are you sure, the BC provider is being added? Maybe there's already one registered that doesn't have the x509 support?

**Comment by drallgood** [comment]
Closing. No response

**Comment by kaanusha** [comment]
PKSigningInformationUtil().loadSigningInformationFromPKCS12AndIntermediateCertificate(passKey,  password, appleFile); is throwing java.security.cert.CertificateException: X.509 not found.

Respective import de.brendamour.jpasskit.signing.PKSigningInformationUtil;

could you please help me in resolving this.

**Comment by techcoreJ** [comment]
Hi, 
I got the same issue in AEM CMS context. 
P/S: It's working well in jpasskit.server (0.0.2-SNAPSHOT)

Hope there have anyone who had solved the issue can share. I'm looking for the root cause.

Regards & Thanks

**Comment by drallgood** [comment]
@techcoreJ Thanks for the report.
Could you please give the latest snapshot version a try? I've updated a few dependencies, hoping that this will fix it.

**Comment by pritchard6782** [comment]
Had the same problem. Turns out it's due to SHA1 support being disabled in the latest versions of java. Currently looking at possible solutions...

**Comment by drallgood** [comment]
@pritchard6782 Awesome. Let me know when you have a better grasp of the issue/solution.

**Comment by pritchard6782** [comment]
Well, spent ages on this and could not find a programmatic solution. Only workaround I could find was to re-enable SHA1 encryption on our JVM. :/

**Comment by drallgood** [comment]
Yeah. Since Apple requires a SHA1 hash of the content, that's probably the only solution.
See https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html#//apple_ref/doc/uid/TP40012195-CH4-SW55

Could you please send a PR for the README that details how to reenable this?

**Comment by drallgood** [comment]
Closing this again

@pritchard6782 Please submit a PR with those changes

**Comment by sascha-hack** [comment]
Was the SHA1 point really the issue?

java.security.cert.CertificateException: X.509 not found

It works fine for me in a JUnit test, but it does not work in a war container on tomcat.

**Comment by sascha-hack** [comment]
Found it. We did update Java and then the SHA1 was disabled again.

/jdk/conf/security/java.security

jdk.certpath.disabledAlgorithms=MD2, MD5, SHA1 jdkCA & usage TLSServer, \
    RSA keySize < 1024, DSA keySize < 1024, EC keySize < 224, \
    include jdk.disabled.namedCurves

Was a combination of the G4 certificate and the java update.
