### ISSUE TITLE
How to restrict sharing of pass?

### ISSUE THREAD

**Issue by rahul33** [drallgood/jpasskit#73]
How to restrict sharing of pass - How to disable the share functionality of a generic pass using jpasskit? Thanks!

**Comment by drallgood** [comment]
@rahul33 
That is not possible. Apple hasn't put anything in place that would allow such a restriction.

**Comment by rahul33** [comment]
Thank you!

**Comment by cmspray** [comment]
@drallgood This is supported now.

https://developer.apple.com/library/archive/documentation/UserExperience/Reference/PassKit_Bundle/RevisionHistory.html#//apple_ref/doc/uid/TP40012026-CH99-SW1

**Comment by drallgood** [comment]
Unfortunately this is the only reference to this key
I'll have to wait for the updated documentation (the team told me it's coming)
