### ISSUE TITLE
How to add a thumbnail to a generic pass?

### ISSUE THREAD

**Issue by rahul33** [drallgood/jpasskit#74]
How to add a thumbnail to a generic pass? Do I just place it in the TemplateFolder? Please advise, thanks!

**Comment by drallgood** [comment]
@rahul33 
Exactly. 
Make sure it's named thumbnail.png and follows Apple's guidelines:
https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html#//apple_ref/doc/uid/TP40012195-CH4-SW52

**Comment by rahul33** [comment]
Thank you!
