### ISSUE TITLE
PKTextAlignmentRight

### ISSUE THREAD

**Issue by rahul33** [drallgood/jpasskit#75]
This is for a generic pass template. I have only one PKField as part of secondaryFields and I would like to align it to the right of the pass. When setting the field I have set the alignment as follows - 
...
_PKField validityDate = new PKField();
validityDate.setTextAlignment(PKTextAlignment.PKTextAlignmentRight);_
...
but the field is always aligned to the left of the pass.

Can you suggest what I might be doing wrong? Is this feature actually accomplishing text alignment within the field, rather than field alignment within the pass? Please advise, thanks!

**Comment by drallgood** [comment]
You're right. According to Apple, the PKTextAlignment is only intended to align the content within a field not the field itself.

**Comment by rahul33** [comment]
thank you!
