### ISSUE TITLE
detect if wallet app exists on phone before downloading passes

### ISSUE THREAD

**Issue by rahul33** [drallgood/jpasskit#77]
Is the PKAddPassesViewController class implemented in jPasskit? This will allow us to use such methods like - canAddPasses, which detects if Wallet app is installed on the phone before attempting to download the passes.

If not, is there something similar that will allow us detect if any wallet/pass supported app is installed on the phone before downloading the pass? 

thanks for all your support!

**Comment by drallgood** [comment]
Hi @rahul33 
No, PKAddPassesViewController is part of Apple's passkit API on iOS and is only available for iOS apps not for web services (which is what jPasskit targets)

Nowadays, it's very unlikely that the Wallet app will not be installed on iOS as most active devices (>99%) run iOS 7 or later. So there should really be no need to detect this. 
If you really want to know whether a particular device supports passes, before downloading, you have two options:

1) If you have an iOS app, you can simply call the mentioned API
2) If you're doing this from a website, simply detect the iOS Version in the browser string.
