### ISSUE TITLE
signer information does not match signer information of other classes in the same package

### ISSUE THREAD

**Issue by uebi-belli** [drallgood/jpasskit#79]
Hello, 

When I run the code generated by maven with arguments clean package, I got the follow error when try to sign the passkit zip:

`Caused by: java.lang.SecurityException: class "org.bouncycastle.asn1.cms.OtherRevocationInfoFormat"'s signer information does not match signer information of other classes in the same package
`

Anyone have some tip to solve that?

**Comment by drallgood** [comment]
According to this http://stackoverflow.com/questions/2877262/java-securityexception-signer-information-does-not-match
there is a duplicate dependency on your class path.

**Comment by uebi-belli** [comment]
Hello drallgood, thank you for your fast response.

I found that post too. I don't have any duplicate dependency in project. The curious is I got this error only when run the code builded by maven. If I run by Eclipse, it works fine.

**Comment by drallgood** [comment]
@uebi-belli hmmm.
Have you checked your dependency tree in maven?
Are you using the same maven version in both instances? (Eclipse sometimes uses an internal version, which might cause issues like this)

**Comment by uebi-belli** [comment]
Here is my log from command mvn dependency:analyze-duplicate


`[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Coworking
[INFO] CoworkingEjb
[INFO] CoworkingWs
[INFO] CoworkingEar
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Coworking 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:analyze-duplicate (default-cli) @ Coworking ---
[INFO] No duplicate dependencies found in <dependencies/> or in <dependencyManagement/>
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building CoworkingEjb 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:analyze-duplicate (default-cli) @ CoworkingEjb ---
[INFO] No duplicate dependencies found in <dependencies/> or in <dependencyManagement/>
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building CoworkingWs 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:analyze-duplicate (default-cli) @ CoworkingWs ---
[INFO] No duplicate dependencies found in <dependencies/> or in <dependencyManagement/>
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building CoworkingEar 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:analyze-duplicate (default-cli) @ CoworkingEar ---
[INFO] No duplicate dependencies found in <dependencies/> or in <dependencyManagement/>
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Coworking .......................................... SUCCESS [  0.458 s]
[INFO] CoworkingEjb ....................................... SUCCESS [  0.011 s]
[INFO] CoworkingWs ........................................ SUCCESS [  0.002 s]
[INFO] CoworkingEar ....................................... SUCCESS [  0.001 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.732 s
[INFO] Finished at: 2017-01-29T18:53:11-02:00
[INFO] Final Memory: 14M/309M
[INFO] ------------------------------------------------------------------------`

**Comment by uebi-belli** [comment]
Hello @drallgood , I found the problem.

You were right, the issue is a duplicated dependency, the org.bouncycastle:bcpkix-jdk15on:jar:1.52:compile dependency.

This happens because the jpasskit have a sign process during maven package, so the signature of classes from jpass's bouncycastle is diffrent from my other jar's bouncycastle. I removed the bouncycastle from my other jar and it worked fine.

Why jpasskit is signed in maven package process?

**Comment by drallgood** [comment]
Hey @uebi-belli  
Glad to hear you could solve this.

The bouncy castle dependency is not needed to sign the maven package. We use GPG there... this is necessary in order to be able to upload the artifact to mvn central.

Instead, we obviously need the library to sign the contents of the passes.

**Comment by mayankaSethitekmindz** [comment]
Hello @uebi-belli  , @drallgood 

I am also facing similar kind of issue ,using jpasskit
java.lang.SecurityException: class "org.bouncycastle.cms.CMSProcessable"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:898)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668).

Can you Please help me with this.
