### ISSUE TITLE
Missing licence information

### ISSUE THREAD

**Issue by Zappes** [drallgood/jpasskit#82]
I would very much like to use jpasskit in a project, but the customer has the reasonable expectation of being provided with licence information for all dependecies. What is the licence for this tool and would it be possible to add this information on github?

**Comment by Zappes** [comment]
I actually found the information now I've looked at the sources and built the maven site - adding a licence file for github might still be nice, though.

**Comment by drallgood** [comment]
Hey @Zappes 
Thanks for the reminder. Totally forgot to add this.

fixed with 560a8a463c299777cf14ae3162aec0537116b45d
