### ISSUE TITLE
Adding Images to passbook

### ISSUE THREAD

**Issue by HenrikSchroers** [drallgood/jpasskit#84]
Hi,

is there a way to add images to the passbook through a given url?
The only way I see it works is putting images in the template folder, but I might want to add an image beside another field.

**Comment by drallgood** [comment]
@HenrikSchroers 
Not 100% sure I understood what you were trying to achieve.
The passes are self contained, so there is no way of just adding a URL to the pass.
jPasskit, however allow you to keep the pass template in memory using PKPassTemplateInMemory.
See 
https://github.com/drallgood/jpasskit/blob/master/jpasskit/src/main/java/de/brendamour/jpasskit/signing/PKPassTemplateInMemory.java

**Comment by HenrikSchroers** [comment]
Just like you can add Fields with value, I'd like to add a field containing an image much like a small thumbnail. The image's source is an URL, so I was asking if there is some kind of method to just pass it's path so it can be displayed correctly, alternatively I could just get the image from the url and pass the image instead. However passing an image object to a field won't do, so is there a way to add an image through it's bytestream or something like that?

**Comment by drallgood** [comment]
@HenrikSchroers 
That is not possible. Apple has defined a fixed set of images (and positions) that you can use in your pass. There is no way of just adding an image as a field. Hence, jPasskit doesn't allow you to do that either.

**Comment by drallgood** [comment]
See also https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html#//apple_ref/doc/uid/TP40012195-CH4-SW1

**Comment by HenrikSchroers** [comment]
Thanks for your help,

I'm using https://github.com/drallgood/jpasskit/blob/master/jpasskit/src/main/java/de/brendamour/jpasskit/signing/PKPassTemplateInMemory.java as you mentioned, and it works fine now. I wasn't aware that thumbnail did exactly what I needed.

**Comment by drallgood** [comment]
Awesome. 
Glad I could help!
