### ISSUE TITLE
PKFileBasedSigningUtil(ObjectMapper objectMapper) deprecated

### ISSUE THREAD

**Issue by Steffeng5** [drallgood/jpasskit#85]
`
 /**
     * @deprecated Please use PKFileBasedSigningUtil(ObjectWriter objectWriter) instead
     * @param objectMapper
     */
    @Deprecated
    public PKFileBasedSigningUtil(ObjectMapper objectMapper) {
        super(objectMapper);
    }
`

Can you change your README to describe how to use PKFileBasedSigningUtil(ObjectWriter objectWriter)?

**Comment by Steffeng5** [comment]
Or change the README to "PKFileBasedSigningUtil pkSigningUtil = new PKFileBasedSigningUtil();"

**Comment by drallgood** [comment]
Hey @Steffeng5 
Not sure I fully understand your question.
There is a section in the README file that specifically describes how to use this:
https://github.com/drallgood/jpasskit#signing-and-zipping-a-pass

**Comment by Steffeng5** [comment]
Hey @drallgood 

yes, but  new PKFileBasedSigningUtil(new ObjectMapper()) is deprecated, so this should be changed to  new PKFileBasedSigningUtil() :-)

**Comment by drallgood** [comment]
oh right.. Sorry. I'll fix it!
Thanks for catching this!
