### ISSUE TITLE
IOS Passes support Code 93 barcode format ?

### ISSUE THREAD

**Issue by kaanusha** [drallgood/jpasskit#88]
Hello Team,

Could you please let me know whether IOS Wallet Passes support Code93 barcode format?
I am currently using JPasskit API for creating passes and is not supporting Code93.

Thanks in advance !!
Anusha

**Comment by drallgood** [comment]
@kaanusha 
The supported barcode formats can be found in Apple‘s PassKit Package Format Reference

https://developer.apple.com/library/content/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/LowerLevel.html#//apple_ref/doc/uid/TP40012026-CH3-SW3

As of today, Code93 is NOT supported
