### ISSUE TITLE
Supported JDK

### ISSUE THREAD

**Issue by vineetravi107** [drallgood/jpasskit#90]
I found a JAR file from https://mvnrepository.com/artifact/de.brendamour/jpasskit/0.0.9. 
I wanted to know if this JAR (jPasskit 0.0.9) will run on Oracle WebLogic server 10.3.6.0 with JDK 1.8 installed?

Is this github project supported for JDK 1.8?

**Comment by drallgood** [comment]
Yes, it does support JDK 8 since it's backwards compatible.
