### ISSUE TITLE
org.bouncycastle.jcajce.provider.asymetric.x509.certificatefactory

### ISSUE THREAD

**Issue by vineetravi107** [drallgood/jpasskit#91]
I'm getting the following error while integrating JAR in my JAVA weblogic server.
![capture](https://user-images.githubusercontent.com/9457234/29503937-8d0214a2-8659-11e7-9db1-cf2f977c1de8.JPG)

**Comment by vineetravi107** [comment]
I found the solution. I copied the JAR file into $Domain/lib folder and restarted the server.

**Comment by drallgood** [comment]
Glad you solved it
