### ISSUE TITLE
org.restlet.engine.connector.ClientConnectionHelper not found

### ISSUE THREAD

**Issue by vineetravi107** [drallgood/jpasskit#92]
I'm getting following error while integrating jPassKit server into Oracle weblogic server JDK 1.8.

![capture](https://user-images.githubusercontent.com/9457234/29808696-c93e8c80-8cb6-11e7-83bf-4a013bc29df7.JPG)

![capture1](https://user-images.githubusercontent.com/9457234/29808698-ca86c7e2-8cb6-11e7-9178-486edd2729e2.JPG)

**Comment by drallgood** [comment]
You're probably missing all dependencies. If you're manually integrating the jPasskit JAR into your project, you need to take care of the dependencies yourself.
This is not the recommended approach though as maven does this for you.
