### ISSUE TITLE
java.lang.ClassNotFoundException: org.restlet.ext.ssl.PkixSslContextFactory

### ISSUE THREAD

**Issue by vineetravi107** [drallgood/jpasskit#93]
I am getting the following issue. Please find the screenshot.

![capture](https://user-images.githubusercontent.com/9457234/29809882-73b4a510-8cbb-11e7-80d1-562e399c664d.JPG)

This issue is similar to #55 
But i am unable to solve by the solution provided.

I am using org.restlet.ext.ssl.jar  to get the org.restlet.ext.ssl.PkixSslContextFactory,class .

When i am using the above jar i am getting  Issue #92 .

**Comment by drallgood** [comment]
You probably need the org.restlet.ext.jsslutils.jar to solve this.

**Comment by vineetravi107** [comment]
Thanks.. this solved my issue.

**Comment by vineetravi107** [comment]
but now I'm getting a linking issue #94
