### ISSUE TITLE
Pass failing to open when NFC dictionary is added

### ISSUE THREAD

**Issue by vineetravi107** [drallgood/jpasskit#96]
I have successfully created a pass with iBeacon, Location, and other required fields and its is working fine in iPhones and Mac, but the moment I add NFC field, I get a error of "Invalid pass. Safari cannot recognize the file". What can be the issue? Is my certificate correct or do I need to add something else?

**Comment by drallgood** [comment]
@vineetravi107 have you checked the relevant logs for error messages as stated in Apple's documentation ?
https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html#//apple_ref/doc/uid/TP40012195-CH4-SW1

**Comment by vineetravi107** [comment]
Here is the relevant logs:

`Sep 14 12:27:19 Web-team-BLR-iPhone-2 MobileSafari(PassKitCore)[328] <Notice>: Signature validation: *** FAILED ***
Sep 14 12:27:19 Web-team-BLR-iPhone-2 MobileSafari(PassKitCore)[328] <Fault>: Invalid data error reading pass pass.com.landmarkrewards.nfcRewardPass/7004031685. Passes with an NFC dictionary or a Personalization JSON file must be signed with an enhanced Passbook certificate.
Sep 14 12:27:19 Web-team-BLR-iPhone-2 MobileSafari(PassKitCore)[328] <Notice>: Invalid data error reading pass pass.com.landmarkrewards.nfcRewardPass/7004031685. Passes with an NFC dictionary or a Personalization JSON file must be signed with an enhanced Passbook certificate.
Sep 14 12:27:19 Web-team-BLR-iPhone-2 MobileSafari[328] <Fault>: PassBook Pass download failed: Error: domain=PKPassKitErrorDomain, code=1`

**Comment by drallgood** [comment]
Well... There is your issue. You need an "enhanced Passbook certificate". No idea what that is or how to get it, though. Please refer to Apple's  Wallet NFC documentation or ask Apple directly.

**Comment by vineetravi107** [comment]
Ok.. I'll contact Apple for the same.
