### ISSUE TITLE
Update Pass info then cause error

### ISSUE THREAD

**Issue by cshijiel** [drallgood/jpasskit#97]
Get pass task (pass type pass.com.qiyi, serial number 0013529801379053, if-modified-since (null); with web service url xxx) encountered error: Received invalid pass data.

How to fix it?

**Comment by cshijiel** [comment]
The Java zip is not same as Linux zip command, maybe it`s the reason.

**Comment by drallgood** [comment]
@cshijiel I don't think so. Have you tried manually downloading and verifying it using the signpass tool?

**Comment by cshijiel** [comment]
I use safari to get this file and add to apple wallet successfully, but when I try to update passbook,then error.

Response Header:
HTTP/1.1 200 OK
Server: Resin/4.0.44
Last-Modified: Mon, 18 Sep 2017 13:07:08 GMT
Content-Disposition: form-data; name="attachment"; filename="pass.pkpass"
Content-Type: application/vnd.apple.pkpass
Date: Mon, 18 Sep 2017 13:07:08 GMT

What`s the probobally reason?
Thanks!

**Comment by drallgood** [comment]
I don't know. Please check the device logs and make sure the provided file is valid

**Comment by drallgood** [comment]
No response
